// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.ships.ship_world;

import com.google.common.collect.ImmutableList;
import gnu.trove.iterator.TIntIterator;
import net.minecraft.block.state.IBlockState;
import net.minecraft.init.Blocks;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.util.math.AxisAlignedBB;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.BlockPos.MutableBlockPos;
import net.minecraft.util.math.ChunkPos;
import net.minecraft.world.World;
import net.minecraft.world.WorldServer;
import net.minecraft.world.chunk.Chunk;
import net.minecraft.world.chunk.storage.ExtendedBlockStorage;
import net.minecraft.world.gen.ChunkProviderServer;
import org.apache.commons.lang3.tuple.ImmutableTriple;
import org.joml.Vector3dc;
import org.valkyrienskies.mod.common.config.VSConfig;
import org.valkyrienskies.mod.common.physics.BlockPhysicsDetails;
import org.valkyrienskies.mod.common.ships.QueryableShipData;
import org.valkyrienskies.mod.common.ships.ShipData;
import org.valkyrienskies.mod.common.ships.block_relocation.BlockFinder;
import org.valkyrienskies.mod.common.ships.block_relocation.IRelocationAwareTile;
import org.valkyrienskies.mod.common.ships.block_relocation.SpatialDetector;
import org.valkyrienskies.mod.common.ships.chunk_claims.VSChunkClaim;
import org.valkyrienskies.mod.common.ships.ship_transform.ShipTransform;
import org.valkyrienskies.mod.common.ships.physics_data.BasicCenterOfMassProvider;
import org.valkyrienskies.mod.common.ships.physics_data.IPhysicsObjectCenterOfMassProvider;
import org.valkyrienskies.mod.common.util.VSMath;
import org.valkyrienskies.mod.common.util.ValkyrienUtils;
import org.valkyrienskies.mod.common.util.multithreaded.CalledFromWrongThreadException;
import org.valkyrienskies.mod.common.util.multithreaded.VSWorldPhysicsLoop;
import javax.annotation.Nonnull;
import java.util.*;

public class WorldServerShipManager implements IPhysObjectWorld {

    /**
     * How far outside a spawning structure's surviving blocks its damage records are still collected
     * and carried. A destroyed position keeps the note of what stood there, has no block to travel
     * with, and can therefore sit outside bounds computed from blocks that remain — one full hull
     * layer's worth is the case worth covering, and this is that in blocks.
     */
    private static final int HOLE_SWEEP_MARGIN = 8;
    private final WorldServer world;
    private final VSWorldPhysicsLoop physicsLoop;
    private final Thread physicsThread;
    private final WorldShipLoadingController loadingController;
    private final Map<UUID, PhysicsObject> loadedShips;
    // Use LinkedHashSet as a queue because it preserves order and doesn't allow duplicates
    private final LinkedHashSet<ImmutableTriple<BlockPos, ShipData, BlockFinder.BlockFinderType>> spawnQueue;
    private final LinkedHashSet<UUID> loadQueue;
    private final LinkedHashSet<UUID> unloadQueue;
    private final LinkedHashSet<UUID> backgroundLoadQueue;
    private final Set<UUID> loadingInBackground;
    private ImmutableList<PhysicsObject> threadSafeLoadedShips;

    public WorldServerShipManager(World world) {
        this.world = (WorldServer) world;
        this.physicsLoop = new VSWorldPhysicsLoop(world);
        this.loadingController = new WorldShipLoadingController(this);
        this.loadedShips = new HashMap<>();
        this.spawnQueue = new LinkedHashSet<>();
        this.loadQueue = new LinkedHashSet<>();
        this.unloadQueue = new LinkedHashSet<>();
        this.backgroundLoadQueue = new LinkedHashSet<>();
        this.loadingInBackground = new HashSet<>();
        this.threadSafeLoadedShips = ImmutableList.of();
        this.physicsThread = new Thread(physicsLoop);
        this.physicsThread.start();
    }

    private void enforceGameThread() {
        if (!world.isCallingFromMinecraftThread()) {
            throw new CalledFromWrongThreadException("Wrong thread calling code: " + Thread.currentThread());
        }
    }

    @Override
    public void onWorldUnload() {
        this.physicsLoop.kill();
    }

    @Override
    public PhysicsObject getPhysObjectFromUUID(@Nonnull UUID shipID) throws CalledFromWrongThreadException {
        enforceGameThread();
        return loadedShips.get(shipID);
    }

    @Nonnull
    @Override
    public List<PhysicsObject> getPhysObjectsInAABB(@Nonnull AxisAlignedBB toCheck) throws CalledFromWrongThreadException {
        enforceGameThread();
        List<PhysicsObject> nearby = new ArrayList<>();
        for (PhysicsObject ship : getAllLoadedPhysObj()) {
            if (toCheck.intersects(ship.getShipBB())) {
                nearby.add(ship);
            }
        }
        return nearby;
    }

    public void tick() {
        // First destroy any ships that want to be destroyed (copy blocks from ship to world, and then unload)
        Iterator<Map.Entry<UUID, PhysicsObject>> iterator = loadedShips.entrySet().iterator();
        while (iterator.hasNext()) {
            PhysicsObject physicsObject = iterator.next().getValue();
            if (physicsObject.shouldShipBeDestroyed()) {
                // Copy ship blocks to the world
                physicsObject.destroyShip();
                // Then remove the ship from the world, and the ship map.
                forgetShip(physicsObject.getShipData());
                iterator.remove();
            }
        }
        // ...and the ships nothing has loaded. The sweep above walks `loadedShips`, so a craft that
        // was emptied or declared finished while unloaded was never asked the question and stayed in
        // the registry for the life of the world — answering position lookups, owning a lane, and
        // needing every caller that produced one to reach in and deregister it by hand. A record
        // exists whether or not a physics object does, so this is where such a craft can be
        // collected at all.
        //
        // TWO ways a record can be finished, and the second was missed here for as long as this
        // sweep existed. DEAD is a decision somebody recorded. BLOCKLESS is a fact about the record:
        // a hull cut out of this world leaves its entry behind owning nothing, and nobody declares
        // it dead — the blocks are simply gone. The sweep above already treats loaded-and-blockless
        // as finished (`shouldShipBeDestroyed`), so this is the same judgement applied to the
        // records that pass never reaches. This comment previously said the block set "is not
        // readable here to be judged on"; that was wrong — `blockPositions` is serialized onto
        // `ShipData` itself and survives with the record, so it is readable in exactly this loop.
        //
        // NULL IS NOT EMPTY. A null block set means the record does not say, and a record that does
        // not say is left alone: absence of an answer is not an answer, and collecting on it would
        // delete craft on the strength of a field nobody filled in.
        //
        // IN USE, not merely "in loadedShips": a ship queued for load, or loading in the background,
        // is in this manager's hands without being in that map, and taking its record away in that
        // window throws out of the world tick on the next chunk-provider pass and takes a dedicated
        // server with it. A dead ship caught mid-load is left alone here and collected by the sweep
        // above once it is loaded, which is one tick later and correct.
        //
        // A ship being SPAWNED is not at risk despite `isShipInUse` not covering the spawn queue:
        // `queueShipSpawn` only queues the record, and `addShip` runs inside `spawnNewShips()` below
        // — after the detector and the chunk injection, so the record enters the registry already
        // owning its blocks, and it does so AFTER this loop within the same tick.
        List<ShipData> finished = null;
        for (Iterator<ShipData> records = QueryableShipData.get(world).iterator(); records.hasNext();) {
            ShipData data = records.next();
            if (isShipInUse(data.getUuid())) {
                continue;
            }
            org.valkyrienskies.mod.common.util.datastructures.IBlockPosSetAABB blocks =
                data.getBlockPositions();
            if (data.isDead() || (blocks != null && blocks.isEmpty())) {
                if (finished == null) {
                    finished = new ArrayList<>();
                }
                finished.add(data);
            }
        }
        // Removed after the walk rather than during it: the registry's iterator is its own, and this
        // loop does not need to know what it promises about removal underneath itself.
        if (finished != null) {
            for (ShipData data : finished) {
                forgetShip(data);
            }
        }
        // Then execute queued ship spawn operations
        spawnNewShips();
        // Then determine which ships to load and unload
        loadingController.determineLoadAndUnload();
        // Then execute queued ship load and unload operations
        loadAndUnloadShips();
        // Then tick all the loaded ships
        for (PhysicsObject ship : getAllLoadedPhysObj()) {
            ship.onTick();
        }
        // Finally, send the players updates about the ships.
        loadingController.sendUpdatesToPlayers();
        // And then update the thread safe ship list.
        this.threadSafeLoadedShips = ImmutableList.copyOf(loadedShips.values());
    }

    private void spawnNewShips() {
        for (final ImmutableTriple<BlockPos, ShipData, BlockFinder.BlockFinderType> spawnData : spawnQueue) {
            final BlockPos physicsInfuserPos = spawnData.getLeft();
            final ShipData toSpawn = spawnData.getMiddle();
            final BlockFinder.BlockFinderType blockBlockFinderType = spawnData.getRight();
            dropOwnBlocklessRemnant(toSpawn.getUuid());
            if (loadedShips.containsKey(toSpawn.getUuid())) {
                throw new IllegalStateException("Tried spawning a ShipData that was already loaded?\n" + toSpawn);
            }
            final SpatialDetector detector = detectShip(world, physicsInfuserPos, blockBlockFinderType);
            if (VSConfig.showAnnoyingDebugOutput) {
                System.out.println("Attempting to spawn " + toSpawn + " on the thread " + Thread.currentThread().getName());
            }
            final String refusal = spawnRefusal(detector);
            if (refusal != null) {
                refuseSpawn(toSpawn, physicsInfuserPos, refusal);
                continue; // Skip ship construction
            }
            // Fill the chunk claims: as far as a detection can reach, so no found block falls outside.
            int radius = VSChunkClaim.RADIUS;
            ChunkPos centerPos = toSpawn.getChunkClaim().getCenterPos();
            for (int chunkX = -radius; chunkX <= radius; chunkX++) {
                for (int chunkZ = -radius; chunkZ <= radius; chunkZ++) {
                    toSpawn.getChunkClaim().addChunkClaim(centerPos.x + chunkX, centerPos.z + chunkZ);
                }
            }
            // When copying the ship chunks we want to keep track of the inertia and center of mass.
            IPhysicsObjectCenterOfMassProvider centerOfMassProvider = new BasicCenterOfMassProvider();
            // Then create the ship chunks
            MutableBlockPos srcLocationPos = new MutableBlockPos();
            BlockPos centerDifference = shipyardOffset(toSpawn.getChunkClaim(), physicsInfuserPos, detector);
            // The ship starts where its anchor stood, and the anchor's shipyard image is wherever the
            // offset put it - which is the region center only when the hull fits around that.
            Vector3dc anchorInYard = VSMath.toVector3d(physicsInfuserPos.add(centerDifference));
            ShipTransform startPose = new ShipTransform(VSMath.toVector3d(physicsInfuserPos), anchorInYard);
            toSpawn.setShipTransform(startPose);
            toSpawn.setPrevTickShipTransform(startPose);
            MutableBlockPos pasteLocationPos = new MutableBlockPos();
            Map<Long, Chunk> copiedChunksMap = new HashMap<>();
            // Bounds of the region being taken out of the world, tracked so that the damage records
            // of positions holding no block (the holes a weapon left) can be carried too - they have
            // nothing to ride along with, since this loop enumerates blocks.
            int damageMinX = Integer.MAX_VALUE, damageMinY = Integer.MAX_VALUE, damageMinZ = Integer.MAX_VALUE;
            int damageMaxX = Integer.MIN_VALUE, damageMaxY = Integer.MIN_VALUE, damageMaxZ = Integer.MIN_VALUE;
            // First, copy the blocks and tiles to the new chunks
            TIntIterator blocksIterator = detector.foundSet.iterator();
            while (blocksIterator.hasNext()) {
                int hashedPos = blocksIterator.next();
                SpatialDetector.setPosWithRespectTo(hashedPos, detector.firstBlock, srcLocationPos);
                // Get the BlockPos from the hashedPos
                pasteLocationPos.setPos(srcLocationPos.getX() + centerDifference.getX(), srcLocationPos.getY() + centerDifference.getY(), srcLocationPos.getZ() + centerDifference.getZ());
                // Then add it to the ShipData block positions set
                toSpawn.blockPositions.add(pasteLocationPos.getX(), pasteLocationPos.getY(), pasteLocationPos.getZ());
                // Then create a chunk to accommodate this block (if one does not already exist).
                int newChunkX = pasteLocationPos.getX() >> 4;
                int newChunkZ = pasteLocationPos.getZ() >> 4;
                long newChunkPosLong = ChunkPos.asLong(newChunkX, newChunkZ);
                if (!copiedChunksMap.containsKey(newChunkPosLong)) {
                    Chunk chunk = new Chunk(world, newChunkX, newChunkZ);
                    copiedChunksMap.put(newChunkPosLong, chunk);
                }
                // Then copy the IBlockState & TileEntity to the new Chunk
                // Get the old world Chunk
                Chunk chunkToSet = world.getChunkFromBlockCoords(srcLocationPos);
                // Get the new Chunk
                Chunk newChunk = copiedChunksMap.get(newChunkPosLong);
                // Then get the old IBlockState, as efficiently as possible
                int storageIndex = srcLocationPos.getY() >> 4;
                // Check that we're placing the block in a valid position
                if (storageIndex < 0 || storageIndex >= chunkToSet.storageArrays.length) {
                    // Invalid position, abort!
                    throw new IllegalStateException("Incorrect block copy!\n" + srcLocationPos);
                }
                IBlockState srcState = chunkToSet.storageArrays[storageIndex].get(srcLocationPos.getX() & 15, srcLocationPos.getY() & 15, srcLocationPos.getZ() & 15);
                // Then paste that IBlockState into the new ship chunk
                int newChunkStorageIndex = pasteLocationPos.getY() >> 4;
                if (newChunk.storageArrays[newChunkStorageIndex] == Chunk.NULL_BLOCK_STORAGE) {
                    newChunk.storageArrays[newChunkStorageIndex] = new ExtendedBlockStorage(newChunkStorageIndex << 4, true);
                }
                newChunk.storageArrays[newChunkStorageIndex].set(pasteLocationPos.getX() & 15, pasteLocationPos.getY() & 15, pasteLocationPos.getZ() & 15, srcState);
                // Carry the block's damage record to its new address, for the same reason the tile
                // entity below is carried: the stage of a block that has no tile of its own is held
                // by position, so an assembly that moves only the block would build a pristine ship
                // out of a wrecked structure - and leave the wreck's records on the empty ground.
                dev.stannismod.stellurgy.damage.DamageState.blockMoved(world, srcLocationPos, pasteLocationPos);
                damageMinX = Math.min(damageMinX, srcLocationPos.getX());
                damageMinY = Math.min(damageMinY, srcLocationPos.getY());
                damageMinZ = Math.min(damageMinZ, srcLocationPos.getZ());
                damageMaxX = Math.max(damageMaxX, srcLocationPos.getX());
                damageMaxY = Math.max(damageMaxY, srcLocationPos.getY());
                damageMaxZ = Math.max(damageMaxZ, srcLocationPos.getZ());
                // If this block is force block, then add it to the activeForcePositions list of the ship.
                if (BlockPhysicsDetails.isBlockProvidingForce(srcState)) {
                    toSpawn.activeForcePositions.add(pasteLocationPos);
                }
                // Also update the center of mass and inertia provider
                centerOfMassProvider.onSetBlockState(toSpawn.getInertiaData(), pasteLocationPos, Blocks.AIR.getDefaultState(), srcState);
                // Then copy the TileEntity (if there is one)
                TileEntity srcTile = world.getTileEntity(srcLocationPos);
                if (srcTile != null) {
                    TileEntity pasteTile;
                    if (srcTile instanceof IRelocationAwareTile) {
                        pasteTile = ((IRelocationAwareTile) srcTile).createRelocatedTile(pasteLocationPos, toSpawn);
                    } else {
                        NBTTagCompound tileEntNBT = srcTile.writeToNBT(new NBTTagCompound());
                        // Change the block position to be inside of the Ship
                        tileEntNBT.setInteger("x", pasteLocationPos.getX());
                        tileEntNBT.setInteger("y", pasteLocationPos.getY());
                        tileEntNBT.setInteger("z", pasteLocationPos.getZ());
                        pasteTile = TileEntity.create(world, tileEntNBT);
                    }
                    // Finally, add the new TileEntity to the new ship chunk.
                    newChunk.addTileEntity(pasteTile);
                }
            }
            // The blocks are carried; now the holes between them, which the loop above could not see.
            // Widened by a margin because the bounds above are drawn around blocks that still EXIST:
            // a structure whose outermost layer was shot away keeps its records outside them. The
            // margin is a bound, not a proof - a hole further out than this than the surviving hull
            // is left behind, and the structural-damage subsystem doc says so.
            if (damageMinX != Integer.MAX_VALUE) {
                final int m = HOLE_SWEEP_MARGIN;
                dev.stannismod.stellurgy.damage.DamageState.holesMoved(world,
                    new BlockPos(damageMinX - m, damageMinY - m, damageMinZ - m),
                    new BlockPos(damageMaxX + m, damageMaxY + m, damageMaxZ + m),
                    centerDifference);
            }
            for (final Chunk chunk : copiedChunksMap.values()) {
                chunk.generateSkylightMap();
            }
            // Then delete the copied blocks from the old chunks
            blocksIterator = detector.foundSet.iterator();
            while (blocksIterator.hasNext()) {
                int hashedPos = blocksIterator.next();
                SpatialDetector.setPosWithRespectTo(hashedPos, detector.firstBlock, srcLocationPos);
                Chunk chunkToSet = world.getChunkFromBlockCoords(srcLocationPos);
                // Then get the old IBlockState, as efficiently as possible
                int storageIndex = srcLocationPos.getY() >> 4;
                // Check that we're placing the block in a valid position
                if (storageIndex < 0 || storageIndex >= chunkToSet.storageArrays.length) {
                    // Invalid position, abort!
                    throw new IllegalStateException("Incorrect block copy!\n" + srcLocationPos);
                }
                IBlockState srcState = chunkToSet.storageArrays[storageIndex].get(srcLocationPos.getX() & 15, srcLocationPos.getY() & 15, srcLocationPos.getZ() & 15);
                // THIS IS TEMP because its extremely inefficient.
                // Come up with a clever way to let clients figure this out in the future.
                world.notifyBlockUpdate(srcLocationPos, srcState, Blocks.AIR.getDefaultState(), 3);
                // Finally, delete the old IBlockState and TileEntity from the old Chunk
                chunkToSet.storageArrays[storageIndex].set(srcLocationPos.getX() & 15, srcLocationPos.getY() & 15, srcLocationPos.getZ() & 15, Blocks.AIR.getDefaultState());
                // Delete the TileEntity at this pos (if there is one)
                world.removeTileEntity(srcLocationPos);
                chunkToSet.markDirty();
            }
            // Then relight the original chunks
            {
                Set<Long> chunksRelit = new HashSet<>();
                blocksIterator = detector.foundSet.iterator();
                while (blocksIterator.hasNext()) {
                    int hashedPos = blocksIterator.next();
                    SpatialDetector.setPosWithRespectTo(hashedPos, detector.firstBlock, srcLocationPos);
                    int changedChunkX = srcLocationPos.getX() >> 4;
                    int changedChunkZ = srcLocationPos.getZ() >> 4;
                    long changedChunkPos = ChunkPos.asLong(changedChunkX, changedChunkZ);
                    if (chunksRelit.contains(changedChunkPos)) {
                        continue;
                    }
                    final Chunk chunk = world.getChunkFromChunkCoords(changedChunkX, changedChunkZ);
                    chunk.generateSkylightMap();
                    chunk.checkLight();
                    chunk.markDirty();
                    chunksRelit.add(changedChunkPos);
                }
            }
            // Then inject the ship chunks into the world
            toSpawn.getChunkClaim().forEach((x, z) -> {
                long chunkLong = ChunkPos.asLong(x, z);
                if (copiedChunksMap.containsKey(chunkLong)) {
                    injectChunkIntoWorldServer(copiedChunksMap.get(chunkLong), x, z);
                } else {
                    injectChunkIntoWorldServer(new Chunk(world, x, z), x, z);
                }
            });
            // Add shipData to the ShipData storage
            QueryableShipData.get(world).addShip(toSpawn);
            // Finally, instantiate the PhysicsObject representation of this ShipData
            PhysicsObject physicsObject = new PhysicsObject(world, toSpawn);
            loadedShips.put(toSpawn.getUuid(), physicsObject);
        }
        spawnQueue.clear();
    }

    /**
     * Clear this world's blockless remnant of the ship about to be spawned under {@code uuid}, if one
     * is there.
     *
     * <p>A ship keeps its identity when it is cut out of one world and re-assembled in another, so a
     * spawn may legitimately arrive under a uuid this world has seen. The only thing that can still
     * hold that uuid here is the SAME ship's remnant: a registry entry (and, for a same-world
     * crossing, possibly a loaded object) left behind after the blocks were cut away. A remnant owns
     * no blocks. It is this ship, not another one, so it is dropped rather than collided with — the
     * spawn below re-registers the identity around the blocks that actually arrived.</p>
     *
     * <p>A holder that owns BLOCKS is a different, live ship and is deliberately left alone: the two
     * throws around this call are what say so, and they must keep firing for that case.</p>
     *
     * <p>The destroy pass at the top of {@link #tick()} already collects a blockless LOADED ship one
     * step before the queue is drained, so in practice only an unloaded remnant reaches here. This is
     * the guard for the paths where that ordering does not hold, and it is placed at the drain rather
     * than at the queue because only here is the answer authoritative: a spawn is queued a tick or
     * more earlier, when the remnant may not exist yet.</p>
     */
    /** The structure a spawn anchored at {@code anchor} would take, found the way the spawn finds it. */
    private static SpatialDetector detectShip(World world, BlockPos anchor, BlockFinder.BlockFinderType type) {
        return BlockFinder.getBlockFinderFor(type, anchor, world, VSConfig.maxDetectedShipSize + 1, true);
    }

    /**
     * Why a spawn anchored at {@code anchor} in {@code world} would be refused, or {@code null} when
     * it would be built — the same detection and the same rule the spawn applies, asked without
     * queueing anything. For a caller about to do something it cannot undo before the spawn runs: a
     * crossing cuts the source ship first, and only then hands the blocks to a spawn.
     */
    public static String spawnRefusalAt(World world, BlockPos anchor, BlockFinder.BlockFinderType type) {
        return spawnRefusal(detectShip(world, anchor, type));
    }

    /**
     * Why the structure a detection found cannot become a ship, or {@code null} when it can: more
     * blocks than {@link VSConfig#maxDetectedShipSize}, attached to bedrock, or continuing past
     * {@link SpatialDetector#MAX_REACH} from its anchor.
     */
    private static String spawnRefusal(SpatialDetector detector) {
        if (detector.cleanHouse) {
            return "attached to bedrock";
        }
        if (detector.foundSet.size() > VSConfig.maxDetectedShipSize) {
            return "more than " + VSConfig.maxDetectedShipSize + " blocks";
        }
        if (detector.reachExceeded) {
            return "extends more than " + SpatialDetector.MAX_REACH + " blocks from its anchor";
        }
        return null;
    }

    /**
     * The record of a ship queued to spawn under {@code uuid} and not built yet, or {@code null}. A
     * caller that queued a ship can name it before it is registered — to park it, for one — and a
     * change made to this record is the one the spawn registers.
     */
    public ShipData queuedSpawn(UUID uuid) {
        for (ImmutableTriple<BlockPos, ShipData, BlockFinder.BlockFinderType> queued : spawnQueue) {
            if (queued.getMiddle().getUuid().equals(uuid)) {
                return queued.getMiddle();
            }
        }
        return null;
    }

    /**
     * Take a ship out of this world for good: out of the registry, and its claim given back so a
     * later ship can be built there. Every path that ends a ship's record goes through here.
     */
    public void forgetShip(ShipData data) {
        QueryableShipData.get(world).removeShip(data);
        ValkyrienUtils.getShipChunkAllocator(world).releaseChunkClaim(data.getChunkClaim());
    }

    /**
     * A queued ship that will not be built: nothing is copied, its blocks stay where they stand, and
     * the claim it was given is handed back — it never held anything.
     */
    private void refuseSpawn(ShipData toSpawn, BlockPos anchor, String reason) {
        ValkyrienUtils.getShipChunkAllocator(world).releaseChunkClaim(toSpawn.getChunkClaim());
        org.apache.logging.log4j.LogManager.getLogger(WorldServerShipManager.class).warn("Refusing to spawn ship {} anchored at {} in dim {}: the structure {}. Its blocks"
                        + " are left in the world.", toSpawn.getUuid(), anchor, world.provider.getDimension(),
                reason);
    }

    /**
     * How far each found block moves when it is copied into the shipyard.
     *
     * <p>Along X and Z the anchor goes to the claim's region center, and the claim reaches as far as
     * the detection could ({@link VSChunkClaim#RADIUS}). Along Y the anchor goes to the region
     * center's height when the whole hull fits around it; a hull reaching further above or below its
     * anchor than that allows is moved just enough to stay inside the world's 0..255, which a hull
     * found in a world always can, since it was found inside them.</p>
     */
    private static BlockPos shipyardOffset(VSChunkClaim claim, BlockPos anchor, SpatialDetector detector) {
        int minY = Integer.MAX_VALUE;
        int maxY = Integer.MIN_VALUE;
        MutableBlockPos pos = new MutableBlockPos();
        TIntIterator blocks = detector.foundSet.iterator();
        while (blocks.hasNext()) {
            SpatialDetector.setPosWithRespectTo(blocks.next(), detector.firstBlock, pos);
            minY = Math.min(minY, pos.getY());
            maxY = Math.max(maxY, pos.getY());
        }
        BlockPos center = claim.getRegionCenter();
        int dy = center.getY() - anchor.getY();
        if (minY <= maxY) {
            dy = Math.max(dy, -minY);
            dy = Math.min(dy, 255 - maxY);
        }
        return new BlockPos(center.getX() - anchor.getX(), dy, center.getZ() - anchor.getZ());
    }

    private void dropOwnBlocklessRemnant(@Nonnull UUID uuid) {
        final PhysicsObject loaded = loadedShips.get(uuid);
        if (loaded != null && loaded.getShipData().getBlockPositions() != null
                && loaded.getShipData().getBlockPositions().isEmpty()) {
            // Exactly what the destroy pass does for a ship with nothing left in it: releases the
            // watchers and deletes the ship chunks (the copy-back step is guarded on a non-empty
            // block set, so nothing is resurrected).
            loaded.destroyShip();
            loadedShips.remove(uuid);
        }
        QueryableShipData.get(world).getShip(uuid).ifPresent(remnant -> {
            if (remnant.getBlockPositions() != null && remnant.getBlockPositions().isEmpty()) {
                forgetShip(remnant);
            }
        });
    }

    private void injectChunkIntoWorldServer(@Nonnull Chunk chunk, int x, int z) {
        ChunkProviderServer provider = world.getChunkProvider();
        // A claim can be handed out again after its ship is gone, and that ship's chunks may still be
        // loaded: unload the one being replaced, or its tile entities and entities stay in the world.
        Chunk replaced = provider.id2ChunkMap.get(ChunkPos.asLong(x, z));
        if (replaced != null && replaced != chunk) {
            replaced.onUnload();
        }
        provider.id2ChunkMap.put(ChunkPos.asLong(x, z), chunk);
        chunk.onLoad();
        chunk.checkLight();
        chunk.markDirty();
    }

    private void loadAndUnloadShips() {
        QueryableShipData queryableShipData = QueryableShipData.get(world);
        // Load the ships that are required immediately.
        for (final UUID toLoadID : loadQueue) {
            Optional<ShipData> toLoadOptional = queryableShipData.getShip(toLoadID);
            if (!toLoadOptional.isPresent()) {
                throw new IllegalStateException("No ship found for ID:\n" + toLoadID);
            }
            ShipData toLoad = toLoadOptional.get();
            // Already loaded is a SATISFIED request, not an error — the same reading the background
            // loop below takes, and for the same reason. queueShipLoad is public and thread safe and
            // says "ensure this ship is loaded"; it is not an assertion about the current state, and
            // its callers are outside this manager's tick (a login path, a watch update, a probe that
            // asks for the whole registry). "Please make sure X is loaded" answered while X is loaded
            // has nothing to do. Throwing here instead put an IllegalStateException in the world tick
            // with nothing between it and the server loop, and took the whole dedicated server down.
            if (loadedShips.containsKey(toLoadID)) {
                loadingInBackground.remove(toLoadID);
                continue;
            }
            // Remove this ship from the background loading set, if it is in it.
            loadingInBackground.remove(toLoadID);
            // Finally, load the ship.
            if (VSConfig.showAnnoyingDebugOutput) {
                System.out.println("Attempting to load ship " + toLoad);
            }
            PhysicsObject physicsObject = new PhysicsObject(world, toLoad);
            PhysicsObject old = loadedShips.put(toLoad.getUuid(), physicsObject);
            if (old != null) {
                throw new IllegalStateException("How did we already have a ship loaded for " + toLoad);
            }
        }
        loadQueue.clear();
        // Load ships that aren't required immediately in the background.
        for (final UUID toLoadID : backgroundLoadQueue) {
            // Skip if this ship is already being loaded in the background,.
            if (loadingInBackground.contains(toLoadID)) {
                continue; // Already loading this ship in the background
            }
            // Already loaded is a SATISFIED background request, not an error. determineLoadAndUnload
            // queues a background load for every ship it finds unloaded and runs immediately before
            // this method on the same tick, so anything that queues an IMMEDIATE load from outside the
            // manager's tick (a player logging in aboard a ship asks for the whole registry) puts the
            // same uuid in both queues. The immediate loop above has just loaded it and dropped it from
            // loadingInBackground, which is why the skip a few lines up does not catch it. Both wanted
            // the ship loaded and the ship is loaded; throwing here instead raised an
            // IllegalStateException out of the world tick, with nothing between it and the server loop,
            // and took the whole dedicated server down.
            if (loadedShips.containsKey(toLoadID)) {
                continue;
            }
            // Then try getting the ShipData for this UUID.
            Optional<ShipData> toLoadOptional = queryableShipData.getShip(toLoadID);
            if (!toLoadOptional.isPresent()) {
                throw new IllegalStateException("No ship found for ID:\n" + toLoadID);
            }
            ShipData toLoad = toLoadOptional.get();
            loadingInBackground.add(toLoadID);
            if (VSConfig.showAnnoyingDebugOutput) {
                System.out.println("Attempting to load " + toLoad + " in the background.");
            }
            ChunkProviderServer chunkProviderServer = world.getChunkProvider();
            for (ChunkPos chunkPos : toLoad.getChunkClaim()) {
                @Nonnull
                Runnable returnTask = () -> {
                    if (VSConfig.showAnnoyingDebugOutput) {
                        System.out.println("Loaded ship chunk " + chunkPos);
                    }
                };
                chunkProviderServer.loadChunk(chunkPos.x, chunkPos.z, returnTask);
            }
        }
        backgroundLoadQueue.clear();
        // Unload far away ships immediately.
        for (final UUID toUnloadID : unloadQueue) {
            // Not loaded is a SATISFIED request, the mirror of the load loop above: queueShipUnload
            // asks for a ship not to be loaded, and one that is already unloaded needs nothing done
            // to it. The state can arrive here legitimately — an unload queued on one tick for a ship
            // something else unloaded first, or a queue that outlived the world's own pass — and
            // dying for it is the same defect wearing the other sign.
            if (!loadedShips.containsKey(toUnloadID)) {
                continue;
            }
            PhysicsObject physicsObject = getPhysObjectFromUUID(toUnloadID);
            if (VSConfig.showAnnoyingDebugOutput) {
                System.out.println("Attempting to unload " + physicsObject);
            }
            physicsObject.unload();
            boolean success = loadedShips.remove(toUnloadID, physicsObject);
            if (!success) {
                throw new IllegalStateException("How did we fail to unload " + physicsObject.getShipData());
            }
        }
        unloadQueue.clear();
    }

    @Nonnull
    @Override
    public Iterable<PhysicsObject> getAllLoadedPhysObj() throws CalledFromWrongThreadException {
        enforceGameThread();
        return loadedShips.values();
    }

    @Nonnull
    @Override
    public ImmutableList<PhysicsObject> getAllLoadedThreadSafe() {
        return threadSafeLoadedShips;
    }

    /**
     * Thread safe way to queue a ship spawn. (Not the same as {@link #queueShipLoad(UUID)}.
     */
    public void queueShipSpawn(@Nonnull ShipData data, @Nonnull BlockPos spawnPos, @Nonnull BlockFinder.BlockFinderType blockFinderType) {
        enforceGameThread();
        this.spawnQueue.add(ImmutableTriple.of(spawnPos, data, blockFinderType));
    }

    /**
     * Is this ship in the manager's hands right now — loaded, queued to load, or streaming its chunks
     * in the background?
     *
     * <p>Anything about to DEREGISTER a ship has to ask THIS and not merely "is it loaded". A ship
     * whose chunks are being streamed has no {@link PhysicsObject} yet, so it answers "not loaded" to
     * {@link #getPhysObjectFromUUID(UUID)} while the loader is still holding its id; removing its
     * {@link ShipData} in that window throws {@code IllegalStateException} out of the world tick from
     * {@link #getBackgroundShipChunks()} on the very next chunk-provider tick, with nothing between
     * the throw and the server loop. The three queues below are the whole of "in the manager's
     * hands", and each of them dereferences its ids against the registry.</p>
     */
    public boolean isShipInUse(@Nonnull UUID shipID) {
        enforceGameThread();
        return loadedShips.containsKey(shipID)
            || loadQueue.contains(shipID)
            || backgroundLoadQueue.contains(shipID)
            || loadingInBackground.contains(shipID);
    }

    @Override
    public void queueShipLoad(@Nonnull UUID shipID) {
        enforceGameThread();
        this.loadQueue.add(shipID);
    }

    @Override
    public void queueShipUnload(@Nonnull UUID shipID) {
        enforceGameThread();
        this.unloadQueue.add(shipID);
    }

    /**
     * Thread safe way to queue a ship to be loaded in the background.
     */
    public void queueShipLoadBackground(@Nonnull UUID shipID) {
        enforceGameThread();
        backgroundLoadQueue.add(shipID);
    }

    /**
     * Used to prevent the world from unloading the chunks of ships loading in background.
     */
    public Iterable<Long> getBackgroundShipChunks() throws CalledFromWrongThreadException {
        enforceGameThread();
        List<Long> backgroundChunks = new ArrayList<>();
        QueryableShipData queryableShipData = QueryableShipData.get(world);
        for (UUID shipID : loadingInBackground) {
            Optional<ShipData> shipDataOptional = queryableShipData.getShip(shipID);
            if (!shipDataOptional.isPresent()) {
                throw new IllegalStateException("Ship data not present for:\n" + shipID);
            }
            backgroundChunks.addAll(shipDataOptional.get().getChunkClaim().getClaimedChunks());
        }
        return backgroundChunks;
    }

    @java.lang.SuppressWarnings("all")
    public WorldServer getWorld() {
        return this.world;
    }

    @java.lang.SuppressWarnings("all")
    public VSWorldPhysicsLoop getPhysicsLoop() {
        return this.physicsLoop;
    }
}
