// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.ships.ship_world;

import com.google.common.collect.ImmutableList;
import gnu.trove.iterator.TIntIterator;
import net.minecraft.block.state.IBlockState;
import net.minecraft.init.Blocks;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.util.math.AxisAlignedBB;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.BlockPos.MutableBlockPos;
import net.minecraft.util.math.ChunkPos;
import net.minecraft.world.World;
import net.minecraft.world.WorldServer;
import net.minecraft.world.chunk.Chunk;
import net.minecraft.world.chunk.storage.ExtendedBlockStorage;
import net.minecraft.world.gen.ChunkProviderServer;
import net.minecraft.world.gen.structure.StructureBoundingBox;
import org.valkyrienskies.mod.common.config.VSConfig;
import org.valkyrienskies.mod.common.physics.BlockPhysicsDetails;
import org.valkyrienskies.mod.common.ships.QueryableShipData;
import org.valkyrienskies.mod.common.ships.ShipData;
import org.valkyrienskies.mod.common.ships.block_relocation.BlockFinder;
import org.valkyrienskies.mod.common.ships.block_relocation.IRelocationAwareTile;
import org.valkyrienskies.mod.common.ships.block_relocation.SpatialDetector;
import org.valkyrienskies.mod.common.ships.physics_data.BasicCenterOfMassProvider;
import org.valkyrienskies.mod.common.ships.physics_data.IPhysicsObjectCenterOfMassProvider;
import org.valkyrienskies.mod.common.util.multithreaded.CalledFromWrongThreadException;
import org.valkyrienskies.mod.common.util.multithreaded.VSWorldPhysicsLoop;
import net.minecraftforge.common.MinecraftForge;
import dev.stannismod.stellurgy.api.event.ShipLifecycleEvent;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.util.*;

public class WorldServerShipManager implements IPhysObjectWorld {

    /**
     * How far outside a spawning structure's surviving blocks its damage records are still collected
     * and carried. A destroyed position keeps the note of what stood there, has no block to travel
     * with, and can therefore sit outside bounds computed from blocks that remain — one full hull
     * layer's worth is the case worth covering, and this is that in blocks.
     */
    private static final int HOLE_SWEEP_MARGIN = 8;
    private final WorldServer world;
    private final VSWorldPhysicsLoop physicsLoop;
    private final Thread physicsThread;
    private final WorldShipLoadingController loadingController;
    private final Map<UUID, PhysicsObject> loadedShips;
    // Use LinkedHashSet as a queue because it preserves order and doesn't allow duplicates
    private final LinkedHashSet<QueuedSpawn> spawnQueue;
    private final LinkedHashSet<UUID> loadQueue;
    private final LinkedHashSet<UUID> unloadQueue;
    private final LinkedHashSet<UUID> backgroundLoadQueue;
    private final Set<UUID> loadingInBackground;
    private ImmutableList<PhysicsObject> threadSafeLoadedShips;
    /**
     * Lifecycle transitions that happened this tick and have not been announced yet.
     *
     * <p>Collected rather than posted at the site, and flushed once the queues above have all been
     * drained. A handler is then free to queue a spawn, a load or an unload of its own — it lands in
     * a queue nothing is iterating, and is acted on next tick — where posting mid-drain would have
     * meant a handler mutating the very collection the loop was walking.</p>
     */
    private final List<ShipLifecycleEvent> pendingLifecycle;
    /**
     * Craft a crossing has DECLARED it is about to cut out of this world, and the dimension each one
     * is going to — consumed by that craft's removal from the registry, which is then announced as a
     * departure instead of a destruction.
     *
     * <p>A departure and a destruction end the same way here — the record leaves the registry — so
     * only the code that knows can tell them apart, and it says so BEFORE it cuts. A mark lives until
     * the removal it predicts (the cut is what causes it) or until the crossing takes it back
     * ({@link #abandonDeparture}); there is no clock on it.</p>
     */
    private final Map<UUID, Integer> departing;

    public WorldServerShipManager(World world) {
        this.world = (WorldServer) world;
        this.physicsLoop = new VSWorldPhysicsLoop(world);
        this.loadingController = new WorldShipLoadingController(this);
        this.loadedShips = new HashMap<>();
        this.spawnQueue = new LinkedHashSet<>();
        this.loadQueue = new LinkedHashSet<>();
        this.unloadQueue = new LinkedHashSet<>();
        this.backgroundLoadQueue = new LinkedHashSet<>();
        this.loadingInBackground = new HashSet<>();
        this.pendingLifecycle = new ArrayList<>();
        this.departing = new HashMap<>();
        this.threadSafeLoadedShips = ImmutableList.of();
        this.physicsThread = new Thread(physicsLoop);
        this.physicsThread.start();
    }

    /**
     * One queued spawn: where to look for the blocks, the record to register them under, how to find
     * them, and WHY the ship is appearing.
     *
     * <p>The cause is carried in from the caller rather than worked out at the drain, because the
     * drain cannot tell a new build from a craft that was cut out of another world and pasted here —
     * both arrive as the same call with the same blocks. Only the caller knows which it asked for,
     * and the difference decides whether a consumer mints a durable record or reattaches to one.</p>
     *
     * <p>The footprint is the region the block search may not leave — the blocks the caller actually
     * placed — and it travels with the spawn for the same reason the cause does: only the caller knows
     * it, and at the drain the world around the craft is indistinguishable from the craft.</p>
     *
     * <p>Value equality across every field, so the enclosing {@code LinkedHashSet} keeps refusing
     * duplicates exactly as it did when this was a triple.</p>
     */
    private static final class QueuedSpawn {
        private final BlockPos spawnPos;
        private final ShipData toSpawn;
        private final BlockFinder.BlockFinderType blockFinderType;
        private final ShipLifecycleEvent.Cause cause;
        private final StructureBoundingBox footprint;

        private QueuedSpawn(BlockPos spawnPos, ShipData toSpawn,
                            BlockFinder.BlockFinderType blockFinderType,
                            ShipLifecycleEvent.Cause cause, StructureBoundingBox footprint) {
            this.spawnPos = spawnPos;
            this.toSpawn = toSpawn;
            this.blockFinderType = blockFinderType;
            this.cause = cause;
            this.footprint = footprint;
        }

        @Override
        public boolean equals(Object other) {
            if (this == other) {
                return true;
            }
            if (!(other instanceof QueuedSpawn)) {
                return false;
            }
            QueuedSpawn that = (QueuedSpawn) other;
            return Objects.equals(spawnPos, that.spawnPos) && toSpawn == that.toSpawn
                    && blockFinderType == that.blockFinderType && cause == that.cause
                    // StructureBoundingBox keeps Object's identity equality, so it is compared by value
                    && Arrays.equals(corners(footprint), corners(that.footprint));
        }

        @Override
        public int hashCode() {
            return Objects.hash(spawnPos, System.identityHashCode(toSpawn), blockFinderType, cause,
                    Arrays.hashCode(corners(footprint)));
        }

        private static int[] corners(StructureBoundingBox box) {
            return new int[]{box.minX, box.minY, box.minZ, box.maxX, box.maxY, box.maxZ};
        }
    }

    private void enforceGameThread() {
        if (!world.isCallingFromMinecraftThread()) {
            throw new CalledFromWrongThreadException("Wrong thread calling code: " + Thread.currentThread());
        }
    }

    @Override
    public void onWorldUnload() {
        this.physicsLoop.kill();
    }

    @Override
    public PhysicsObject getPhysObjectFromUUID(@Nonnull UUID shipID) throws CalledFromWrongThreadException {
        enforceGameThread();
        return loadedShips.get(shipID);
    }

    @Nonnull
    @Override
    public List<PhysicsObject> getPhysObjectsInAABB(@Nonnull AxisAlignedBB toCheck) throws CalledFromWrongThreadException {
        enforceGameThread();
        List<PhysicsObject> nearby = new ArrayList<>();
        for (PhysicsObject ship : getAllLoadedPhysObj()) {
            if (toCheck.intersects(ship.getShipBB())) {
                nearby.add(ship);
            }
        }
        return nearby;
    }

    public void tick() {
        // First destroy any ships that want to be destroyed (copy blocks from ship to world, and then unload)
        Iterator<Map.Entry<UUID, PhysicsObject>> iterator = loadedShips.entrySet().iterator();
        while (iterator.hasNext()) {
            PhysicsObject physicsObject = iterator.next().getValue();
            if (physicsObject.shouldShipBeDestroyed()) {
                // Copy ship blocks to the world
                physicsObject.destroyShip();
                // Then remove the ship from the world, and the ship map.
                removeRecord(physicsObject.getShipData());
                iterator.remove();
            }
        }
        // ...and the ships nothing has loaded. The sweep above walks `loadedShips`, so a craft that
        // was emptied or declared finished while unloaded was never asked the question and stayed in
        // the registry for the life of the world — answering position lookups, owning a lane, and
        // needing every caller that produced one to reach in and deregister it by hand. A record
        // exists whether or not a physics object does, so this is where such a craft can be
        // collected at all.
        //
        // TWO ways a record can be finished, and the second was missed here for as long as this
        // sweep existed. DEAD is a decision somebody recorded. BLOCKLESS is a fact about the record:
        // a hull cut out of this world leaves its entry behind owning nothing, and nobody declares
        // it dead — the blocks are simply gone. The sweep above already treats loaded-and-blockless
        // as finished (`shouldShipBeDestroyed`), so this is the same judgement applied to the
        // records that pass never reaches. This comment previously said the block set "is not
        // readable here to be judged on"; that was wrong — `blockPositions` is serialized onto
        // `ShipData` itself and survives with the record, so it is readable in exactly this loop.
        //
        // NULL IS NOT EMPTY. A null block set means the record does not say, and a record that does
        // not say is left alone: absence of an answer is not an answer, and collecting on it would
        // delete craft on the strength of a field nobody filled in.
        //
        // IN USE, not merely "in loadedShips": a ship queued for load, or loading in the background,
        // is in this manager's hands without being in that map, and taking its record away in that
        // window throws out of the world tick on the next chunk-provider pass and takes a dedicated
        // server with it. A dead ship caught mid-load is left alone here and collected by the sweep
        // above once it is loaded, which is one tick later and correct.
        //
        // A ship being SPAWNED is not at risk despite `isShipInUse` not covering the spawn queue:
        // `queueShipSpawn` only queues the record, and `addShip` runs inside `spawnNewShips()` below
        // — after the detector and the chunk injection, so the record enters the registry already
        // owning its blocks, and it does so AFTER this loop within the same tick.
        List<ShipData> finished = null;
        for (Iterator<ShipData> records = QueryableShipData.get(world).iterator(); records.hasNext();) {
            ShipData data = records.next();
            if (isShipInUse(data.getUuid())) {
                continue;
            }
            org.valkyrienskies.mod.common.util.datastructures.IBlockPosSetAABB blocks =
                data.getBlockPositions();
            if (data.isDead() || (blocks != null && blocks.isEmpty())) {
                if (finished == null) {
                    finished = new ArrayList<>();
                }
                finished.add(data);
            }
        }
        // Removed after the walk rather than during it: the registry's iterator is its own, and this
        // loop does not need to know what it promises about removal underneath itself.
        // Announced like every other removal: a record collected here leaves the registry exactly as
        // a destroyed loaded ship does, and a crossing out of an UNLOADED source ends HERE — so this is
        // where its departure is said, or nobody says it.
        if (finished != null) {
            for (ShipData data : finished) {
                removeRecord(data);
            }
        }
        // Then execute queued ship spawn operations
        spawnNewShips();
        // Then determine which ships to load and unload
        loadingController.determineLoadAndUnload();
        // Then execute queued ship load and unload operations
        loadAndUnloadShips();
        // Then announce everything that appeared or vanished above, now that no queue is being walked
        publishLifecycleEvents();
        // Then tick all the loaded ships
        for (PhysicsObject ship : getAllLoadedPhysObj()) {
            ship.onTick();
        }
        // Finally, send the players updates about the ships.
        loadingController.sendUpdatesToPlayers();
        // And then update the thread safe ship list.
        this.threadSafeLoadedShips = ImmutableList.copyOf(loadedShips.values());
        // ...and announce the ships that became USABLE on this tick. The substrate does not step a
        // ship until it is past its settling delay and its surrounding-chunk cache is filled, and both
        // halves are decided inside `onTick` above, so this tick is the one the fact became true on.
        // LAST, after the thread-safe list: a handler resolves the craft it hears about, and most
        // lookups read that list — announced before it, a ship loaded this tick would be "usable" and
        // unfindable at once. Once per ship object, which is once per load.
        //
        // NOT `isPhysicsEnabled`, deliberately: that is an operational switch somebody throws, so a
        // parked craft nobody has commanded is fully loaded with it false. Requiring it made "usable"
        // mean "is anyone flying this", and a caller waiting to BEGIN flying waited for a state its
        // own next action causes — 1 red became 42 on the first gate that used it.
        for (PhysicsObject ship : getAllLoadedPhysObj()) {
            if (!ship.isUsableAnnounced() && ship.isPhysicsReady()
                    && ship.getCachedSurroundingChunks() != null) {
                ship.markUsableAnnounced();
                ShipData data = ship.getShipData();
                pendingLifecycle.add(new ShipLifecycleEvent.ShipUsable(world, data.getUuid(),
                        data.getStellurgyDurableId()));
            }
        }
        publishLifecycleEvents();
    }

    private void spawnNewShips() {
        // Observed from the test tree, not from here: a test-only mixin records this method's entry
        // and return and wraps the flood-detector call below, so a queued ship that never appears
        // can be told apart between "never processed", "dropped before registering" and "registered
        // then destroyed". It targets THIS method, so the detector call must stay in it.
        for (final QueuedSpawn spawnData : spawnQueue) {
            final BlockPos physicsInfuserPos = spawnData.spawnPos;
            final ShipData toSpawn = spawnData.toSpawn;
            final BlockFinder.BlockFinderType blockBlockFinderType = spawnData.blockFinderType;
            dropOwnBlocklessRemnant(toSpawn.getUuid());
            if (loadedShips.containsKey(toSpawn.getUuid())) {
                throw new IllegalStateException("Tried spawning a ShipData that was already loaded?\n" + toSpawn);
            }
            final SpatialDetector detector = BlockFinder.getBlockFinderFor(blockBlockFinderType, physicsInfuserPos, world, spawnSizeLimit(), SPAWN_CHECKS_CORNERS, spawnData.footprint);
            if (VSConfig.showAnnoyingDebugOutput) {
                System.out.println("Attempting to spawn " + toSpawn + " on the thread " + Thread.currentThread().getName());
            }
            final SpawnRefusal refusal = refusalOf(detector);
            if (refusal != null) {
                // A caller that cares asks refusalFor BEFORE queueing; this line is for one that did not.
                System.err.println("Ship spawn refused (" + refusal + ") at " + physicsInfuserPos);
                continue; // Skip ship construction
            }
            // Fill the chunk claims
            int radius = 7;
            // TEMP CODE
            // Eventually want to create mechanisms that control how many chunks are allocated to a ship
            // But for now, lets just give them a bunch of chunks.
            ChunkPos centerPos = toSpawn.getChunkClaim().getCenterPos();
            for (int chunkX = -radius; chunkX <= radius; chunkX++) {
                for (int chunkZ = -radius; chunkZ <= radius; chunkZ++) {
                    toSpawn.getChunkClaim().addChunkClaim(centerPos.x + chunkX, centerPos.z + chunkZ);
                }
            }
            // When copying the ship chunks we want to keep track of the inertia and center of mass.
            IPhysicsObjectCenterOfMassProvider centerOfMassProvider = new BasicCenterOfMassProvider();
            // Then create the ship chunks
            MutableBlockPos srcLocationPos = new MutableBlockPos();
            BlockPos centerDifference = toSpawn.getChunkClaim().getRegionCenter().subtract(physicsInfuserPos);
            MutableBlockPos pasteLocationPos = new MutableBlockPos();
            Map<Long, Chunk> copiedChunksMap = new HashMap<>();
            // Bounds of the region being taken out of the world, tracked so that the damage records
            // of positions holding no block (the holes a weapon left) can be carried too - they have
            // nothing to ride along with, since this loop enumerates blocks.
            int damageMinX = Integer.MAX_VALUE, damageMinY = Integer.MAX_VALUE, damageMinZ = Integer.MAX_VALUE;
            int damageMaxX = Integer.MIN_VALUE, damageMaxY = Integer.MIN_VALUE, damageMaxZ = Integer.MIN_VALUE;
            // First, copy the blocks and tiles to the new chunks
            TIntIterator blocksIterator = detector.foundSet.iterator();
            while (blocksIterator.hasNext()) {
                int hashedPos = blocksIterator.next();
                SpatialDetector.setPosWithRespectTo(hashedPos, detector.firstBlock, srcLocationPos);
                // Get the BlockPos from the hashedPos
                pasteLocationPos.setPos(srcLocationPos.getX() + centerDifference.getX(), srcLocationPos.getY() + centerDifference.getY(), srcLocationPos.getZ() + centerDifference.getZ());
                // Then add it to the ShipData block positions set
                toSpawn.blockPositions.add(pasteLocationPos.getX(), pasteLocationPos.getY(), pasteLocationPos.getZ());
                // Then create a chunk to accommodate this block (if one does not already exist).
                int newChunkX = pasteLocationPos.getX() >> 4;
                int newChunkZ = pasteLocationPos.getZ() >> 4;
                long newChunkPosLong = ChunkPos.asLong(newChunkX, newChunkZ);
                if (!copiedChunksMap.containsKey(newChunkPosLong)) {
                    Chunk chunk = new Chunk(world, newChunkX, newChunkZ);
                    copiedChunksMap.put(newChunkPosLong, chunk);
                }
                // Then copy the IBlockState & TileEntity to the new Chunk
                // Get the old world Chunk
                Chunk chunkToSet = world.getChunkFromBlockCoords(srcLocationPos);
                // Get the new Chunk
                Chunk newChunk = copiedChunksMap.get(newChunkPosLong);
                // Then get the old IBlockState, as efficiently as possible
                int storageIndex = srcLocationPos.getY() >> 4;
                // Check that we're placing the block in a valid position
                if (storageIndex < 0 || storageIndex >= chunkToSet.storageArrays.length) {
                    // Invalid position, abort!
                    throw new IllegalStateException("Incorrect block copy!\n" + srcLocationPos);
                }
                IBlockState srcState = chunkToSet.storageArrays[storageIndex].get(srcLocationPos.getX() & 15, srcLocationPos.getY() & 15, srcLocationPos.getZ() & 15);
                // Then paste that IBlockState into the new ship chunk
                int newChunkStorageIndex = pasteLocationPos.getY() >> 4;
                if (newChunk.storageArrays[newChunkStorageIndex] == Chunk.NULL_BLOCK_STORAGE) {
                    newChunk.storageArrays[newChunkStorageIndex] = new ExtendedBlockStorage(newChunkStorageIndex << 4, true);
                }
                newChunk.storageArrays[newChunkStorageIndex].set(pasteLocationPos.getX() & 15, pasteLocationPos.getY() & 15, pasteLocationPos.getZ() & 15, srcState);
                // Carry the block's damage record to its new address, for the same reason the tile
                // entity below is carried: the stage of a block that has no tile of its own is held
                // by position, so an assembly that moves only the block would build a pristine ship
                // out of a wrecked structure - and leave the wreck's records on the empty ground.
                dev.stannismod.stellurgy.damage.DamageState.blockMoved(world, srcLocationPos, pasteLocationPos);
                damageMinX = Math.min(damageMinX, srcLocationPos.getX());
                damageMinY = Math.min(damageMinY, srcLocationPos.getY());
                damageMinZ = Math.min(damageMinZ, srcLocationPos.getZ());
                damageMaxX = Math.max(damageMaxX, srcLocationPos.getX());
                damageMaxY = Math.max(damageMaxY, srcLocationPos.getY());
                damageMaxZ = Math.max(damageMaxZ, srcLocationPos.getZ());
                // If this block is force block, then add it to the activeForcePositions list of the ship.
                if (BlockPhysicsDetails.isBlockProvidingForce(srcState)) {
                    toSpawn.activeForcePositions.add(pasteLocationPos);
                }
                // Also update the center of mass and inertia provider
                centerOfMassProvider.onSetBlockState(toSpawn.getInertiaData(), pasteLocationPos, Blocks.AIR.getDefaultState(), srcState);
                // Then copy the TileEntity (if there is one)
                TileEntity srcTile = world.getTileEntity(srcLocationPos);
                if (srcTile != null) {
                    TileEntity pasteTile;
                    if (srcTile instanceof IRelocationAwareTile) {
                        pasteTile = ((IRelocationAwareTile) srcTile).createRelocatedTile(pasteLocationPos, toSpawn);
                    } else {
                        NBTTagCompound tileEntNBT = srcTile.writeToNBT(new NBTTagCompound());
                        // Change the block position to be inside of the Ship
                        tileEntNBT.setInteger("x", pasteLocationPos.getX());
                        tileEntNBT.setInteger("y", pasteLocationPos.getY());
                        tileEntNBT.setInteger("z", pasteLocationPos.getZ());
                        pasteTile = TileEntity.create(world, tileEntNBT);
                    }
                    // Finally, add the new TileEntity to the new ship chunk.
                    newChunk.addTileEntity(pasteTile);
                }
            }
            // The blocks are carried; now the holes between them, which the loop above could not see.
            // Widened by a margin because the bounds above are drawn around blocks that still EXIST:
            // a structure whose outermost layer was shot away keeps its records outside them. The
            // margin is a bound, not a proof - a hole further out than this than the surviving hull
            // is left behind, and the structural-damage subsystem doc says so.
            if (damageMinX != Integer.MAX_VALUE) {
                final int m = HOLE_SWEEP_MARGIN;
                dev.stannismod.stellurgy.damage.DamageState.holesMoved(world,
                    new BlockPos(damageMinX - m, damageMinY - m, damageMinZ - m),
                    new BlockPos(damageMaxX + m, damageMaxY + m, damageMaxZ + m),
                    centerDifference);
            }
            for (final Chunk chunk : copiedChunksMap.values()) {
                chunk.generateSkylightMap();
            }
            // Then delete the copied blocks from the old chunks
            blocksIterator = detector.foundSet.iterator();
            while (blocksIterator.hasNext()) {
                int hashedPos = blocksIterator.next();
                SpatialDetector.setPosWithRespectTo(hashedPos, detector.firstBlock, srcLocationPos);
                Chunk chunkToSet = world.getChunkFromBlockCoords(srcLocationPos);
                // Then get the old IBlockState, as efficiently as possible
                int storageIndex = srcLocationPos.getY() >> 4;
                // Check that we're placing the block in a valid position
                if (storageIndex < 0 || storageIndex >= chunkToSet.storageArrays.length) {
                    // Invalid position, abort!
                    throw new IllegalStateException("Incorrect block copy!\n" + srcLocationPos);
                }
                IBlockState srcState = chunkToSet.storageArrays[storageIndex].get(srcLocationPos.getX() & 15, srcLocationPos.getY() & 15, srcLocationPos.getZ() & 15);
                // THIS IS TEMP because its extremely inefficient.
                // Come up with a clever way to let clients figure this out in the future.
                world.notifyBlockUpdate(srcLocationPos, srcState, Blocks.AIR.getDefaultState(), 3);
                // Finally, delete the old IBlockState and TileEntity from the old Chunk
                chunkToSet.storageArrays[storageIndex].set(srcLocationPos.getX() & 15, srcLocationPos.getY() & 15, srcLocationPos.getZ() & 15, Blocks.AIR.getDefaultState());
                // Delete the TileEntity at this pos (if there is one)
                world.removeTileEntity(srcLocationPos);
                chunkToSet.markDirty();
            }
            // Then relight the original chunks
            {
                Set<Long> chunksRelit = new HashSet<>();
                blocksIterator = detector.foundSet.iterator();
                while (blocksIterator.hasNext()) {
                    int hashedPos = blocksIterator.next();
                    SpatialDetector.setPosWithRespectTo(hashedPos, detector.firstBlock, srcLocationPos);
                    int changedChunkX = pasteLocationPos.getX() >> 4;
                    int changedChunkZ = pasteLocationPos.getZ() >> 4;
                    long changedChunkPos = ChunkPos.asLong(changedChunkX, changedChunkZ);
                    if (chunksRelit.contains(changedChunkPos)) {
                        continue;
                    }
                    final Chunk chunk = world.getChunkFromChunkCoords(changedChunkX, changedChunkZ);
                    chunk.generateSkylightMap();
                    chunk.checkLight();
                    chunk.markDirty();
                    chunksRelit.add(changedChunkPos);
                }
            }
            // Then inject the ship chunks into the world
            toSpawn.getChunkClaim().forEach((x, z) -> {
                long chunkLong = ChunkPos.asLong(x, z);
                if (copiedChunksMap.containsKey(chunkLong)) {
                    injectChunkIntoWorldServer(copiedChunksMap.get(chunkLong), x, z);
                } else {
                    injectChunkIntoWorldServer(new Chunk(world, x, z), x, z);
                }
            });
            // Add shipData to the ShipData storage
            QueryableShipData.get(world).addShip(toSpawn);
            // Finally, instantiate the PhysicsObject representation of this ShipData
            PhysicsObject physicsObject = new PhysicsObject(world, toSpawn);
            loadedShips.put(toSpawn.getUuid(), physicsObject);
            // The ship is now resolvable by id: this is the naming edge for a spawn.
            noteNamed(toSpawn, spawnData.cause);
        }
        spawnQueue.clear();
    }

    /**
     * Clear this world's blockless remnant of the ship about to be spawned under {@code uuid}, if one
     * is there.
     *
     * <p>A ship keeps its identity when it is cut out of one world and re-assembled in another, so a
     * spawn may legitimately arrive under a uuid this world has seen. The only thing that can still
     * hold that uuid here is the SAME ship's remnant: a registry entry (and, for a same-world
     * crossing, possibly a loaded object) left behind after the blocks were cut away. A remnant owns
     * no blocks. It is this ship, not another one, so it is dropped rather than collided with — the
     * spawn below re-registers the identity around the blocks that actually arrived.</p>
     *
     * <p>A holder that owns BLOCKS is a different, live ship and is deliberately left alone: the two
     * throws around this call are what say so, and they must keep firing for that case.</p>
     *
     * <p>The destroy pass at the top of {@link #tick()} already collects a blockless LOADED ship one
     * step before the queue is drained, so in practice only an unloaded remnant reaches here. This is
     * the guard for the paths where that ordering does not hold, and it is placed at the drain rather
     * than at the queue because only here is the answer authoritative: a spawn is queued a tick or
     * more earlier, when the remnant may not exist yet.</p>
     */
    private void dropOwnBlocklessRemnant(@Nonnull UUID uuid) {
        final PhysicsObject loaded = loadedShips.get(uuid);
        if (loaded != null && loaded.getShipData().getBlockPositions() != null
                && loaded.getShipData().getBlockPositions().isEmpty()) {
            // Exactly what the destroy pass does for a ship with nothing left in it: releases the
            // watchers and deletes the ship chunks (the copy-back step is guarded on a non-empty
            // block set, so nothing is resurrected).
            loaded.destroyShip();
            loadedShips.remove(uuid);
            removeRecord(loaded.getShipData());
        }
        // Announced even though the spawn a few lines below re-registers the same identity: the
        // registration a consumer was holding really does end here, and a consumer that saw only the
        // re-registration would keep state built against the remnant.
        Optional<ShipData> remnant = QueryableShipData.get(world).getShip(uuid);
        if (remnant.isPresent() && remnant.get().getBlockPositions() != null
                && remnant.get().getBlockPositions().isEmpty()) {
            removeRecord(remnant.get());
        }
    }

    /**
     * End {@code ship}'s registration in this world: announce it and remove the record — and do
     * neither if that record is no longer the one registered under its uuid.
     *
     * <p><b>The announcement belongs to the RECORD, not to the physics object.</b> A registration has
     * two halves — the registry entry and, while loaded, its ship object — and they can be taken down
     * on different paths: an assembly re-using an identity deregisters the blockless entry first
     * ({@link #deregisterBlocklessRemnant}), and the spawn drain then destroys the object it left
     * loaded. Announcing each half said the craft ended twice; measured 2026-10-06 on a same-world
     * crossing, a {@code DEPARTED} immediately followed, in the same tick, by a {@code DESTROYED} for
     * the same vessel, because the first consumed the declared departure. So the entry's removal is
     * the one announcement, and a half whose entry is already gone announces nothing.</p>
     */
    private void removeRecord(@Nonnull ShipData ship) {
        Optional<ShipData> registered = QueryableShipData.get(world).getShip(ship.getUuid());
        if (!registered.isPresent() || registered.get() != ship) {
            return;
        }
        noteRemoved(ship);
        QueryableShipData.get(world).removeShip(ship);
    }

    /**
     * Deregister {@code uuid}'s record if it is a BLOCKLESS remnant — for an assembly about to re-use
     * that identity — and announce the removal like any other. Answers whether a record was removed.
     *
     * <p>Here and not in the caller because every removal from the registry is a lifecycle edge, and
     * the manager is the one place that announces them: a remnant deleted from outside would leave
     * the registration a consumer was holding ended with nothing said.</p>
     */
    public boolean deregisterBlocklessRemnant(@Nonnull UUID uuid) {
        enforceGameThread();
        Optional<ShipData> remnant = QueryableShipData.get(world).getShip(uuid);
        if (!remnant.isPresent() || remnant.get().getBlockPositions() == null
                || !remnant.get().getBlockPositions().isEmpty()) {
            return false;
        }
        removeRecord(remnant.get());
        return true;
    }

    /**
     * A crossing is about to cut {@code uuid} out of this world into {@code destinationDim}. Declared
     * BEFORE the cut, so the removal it causes is announced as a departure by the code that knows,
     * rather than as a destruction.
     */
    public void declareDeparture(@Nonnull UUID uuid, int destinationDim) {
        enforceGameThread();
        departing.put(uuid, destinationDim);
    }

    /** The declared departure did not happen — nothing was cut — so a later removal of this craft
     *  would be a real destruction. */
    public void abandonDeparture(@Nonnull UUID uuid) {
        enforceGameThread();
        departing.remove(uuid);
    }

    /**
     * Record a naming for announcement at the end of this pass.
     *
     * <p>Both identities are read HERE, while the record is in hand.</p>
     */
    private void noteNamed(@Nullable ShipData ship, ShipLifecycleEvent.Cause cause) {
        if (ship == null) {
            return;
        }
        pendingLifecycle.add(new ShipLifecycleEvent.ShipNamed(world, ship.getUuid(),
                ship.getStellurgyDurableId(), cause));
    }

    /** Record that the ship object of a still-registered craft was dropped. */
    private void noteUnloaded(@Nullable ShipData ship) {
        if (ship == null) {
            return;
        }
        pendingLifecycle.add(new ShipLifecycleEvent.ShipUnnamed(world, ship.getUuid(),
                ship.getStellurgyDurableId(), ShipLifecycleEvent.Cause.UNLOADED));
    }

    /**
     * Record that a craft's registration in this world ENDED — called only by {@link #removeRecord},
     * which every removal path goes through, and before the removal, while its durable id can still
     * be read off it.
     *
     * <p>A declared departure turns the removal into a {@link ShipLifecycleEvent.ShipDeparted} and is
     * consumed by it; any other removal is a {@link ShipLifecycleEvent.Cause#DESTROYED}.</p>
     */
    private void noteRemoved(@Nullable ShipData ship) {
        if (ship == null) {
            return;
        }
        Integer destination = departing.remove(ship.getUuid());
        pendingLifecycle.add(destination != null
                ? new ShipLifecycleEvent.ShipDeparted(world, ship.getUuid(),
                        ship.getStellurgyDurableId(), destination)
                : new ShipLifecycleEvent.ShipUnnamed(world, ship.getUuid(),
                        ship.getStellurgyDurableId(), ShipLifecycleEvent.Cause.DESTROYED));
    }

    /**
     * Announce this tick's lifecycle transitions, in the order they happened.
     *
     * <p>Drained into a local copy first: a handler is allowed to queue ship work, and a spawn it
     * queues could otherwise append to the list being iterated. Anything a handler causes is
     * announced on the tick it actually happens, not folded into this one.</p>
     */
    private void publishLifecycleEvents() {
        if (pendingLifecycle.isEmpty()) {
            return;
        }
        List<ShipLifecycleEvent> toPublish = new ArrayList<>(pendingLifecycle);
        pendingLifecycle.clear();
        for (ShipLifecycleEvent event : toPublish) {
            MinecraftForge.EVENT_BUS.post(event);
        }
    }

    private void injectChunkIntoWorldServer(@Nonnull Chunk chunk, int x, int z) {
        ChunkProviderServer provider = world.getChunkProvider();
        provider.id2ChunkMap.put(ChunkPos.asLong(x, z), chunk);
        chunk.onLoad();
        chunk.checkLight();
        chunk.markDirty();
    }

    private void loadAndUnloadShips() {
        QueryableShipData queryableShipData = QueryableShipData.get(world);
        // Load the ships that are required immediately.
        for (final UUID toLoadID : loadQueue) {
            Optional<ShipData> toLoadOptional = queryableShipData.getShip(toLoadID);
            if (!toLoadOptional.isPresent()) {
                throw new IllegalStateException("No ship found for ID:\n" + toLoadID);
            }
            ShipData toLoad = toLoadOptional.get();
            // Already loaded is a SATISFIED request, not an error — the same reading the background
            // loop below takes, and for the same reason. queueShipLoad is public and thread safe and
            // says "ensure this ship is loaded"; it is not an assertion about the current state, and
            // its callers are outside this manager's tick (a login path, a watch update, a probe that
            // asks for the whole registry). "Please make sure X is loaded" answered while X is loaded
            // has nothing to do. Throwing here instead put an IllegalStateException in the world tick
            // with nothing between it and the server loop, and took the whole dedicated server down.
            if (loadedShips.containsKey(toLoadID)) {
                loadingInBackground.remove(toLoadID);
                continue;
            }
            // Remove this ship from the background loading set, if it is in it.
            loadingInBackground.remove(toLoadID);
            // Finally, load the ship.
            if (VSConfig.showAnnoyingDebugOutput) {
                System.out.println("Attempting to load ship " + toLoad);
            }
            PhysicsObject physicsObject = new PhysicsObject(world, toLoad);
            PhysicsObject old = loadedShips.put(toLoad.getUuid(), physicsObject);
            if (old != null) {
                throw new IllegalStateException("How did we already have a ship loaded for " + toLoad);
            }
            // The naming edge for a ship that already existed. A background load reaches this same
            // loop once the controller promotes it, so there is one edge per load however it started.
            noteNamed(toLoad, ShipLifecycleEvent.Cause.LOADED);
        }
        loadQueue.clear();
        // Load ships that aren't required immediately in the background.
        for (final UUID toLoadID : backgroundLoadQueue) {
            // Skip if this ship is already being loaded in the background,.
            if (loadingInBackground.contains(toLoadID)) {
                continue; // Already loading this ship in the background
            }
            // Already loaded is a SATISFIED background request, not an error. determineLoadAndUnload
            // queues a background load for every ship it finds unloaded and runs immediately before
            // this method on the same tick, so anything that queues an IMMEDIATE load from outside the
            // manager's tick (a player logging in aboard a ship asks for the whole registry) puts the
            // same uuid in both queues. The immediate loop above has just loaded it and dropped it from
            // loadingInBackground, which is why the skip a few lines up does not catch it. Both wanted
            // the ship loaded and the ship is loaded; throwing here instead raised an
            // IllegalStateException out of the world tick, with nothing between it and the server loop,
            // and took the whole dedicated server down.
            if (loadedShips.containsKey(toLoadID)) {
                continue;
            }
            // Then try getting the ShipData for this UUID.
            Optional<ShipData> toLoadOptional = queryableShipData.getShip(toLoadID);
            if (!toLoadOptional.isPresent()) {
                throw new IllegalStateException("No ship found for ID:\n" + toLoadID);
            }
            ShipData toLoad = toLoadOptional.get();
            loadingInBackground.add(toLoadID);
            if (VSConfig.showAnnoyingDebugOutput) {
                System.out.println("Attempting to load " + toLoad + " in the background.");
            }
            ChunkProviderServer chunkProviderServer = world.getChunkProvider();
            for (ChunkPos chunkPos : toLoad.getChunkClaim()) {
                @Nonnull
                Runnable returnTask = () -> {
                    if (VSConfig.showAnnoyingDebugOutput) {
                        System.out.println("Loaded ship chunk " + chunkPos);
                    }
                };
                chunkProviderServer.loadChunk(chunkPos.x, chunkPos.z, returnTask);
            }
        }
        backgroundLoadQueue.clear();
        // Unload far away ships immediately.
        for (final UUID toUnloadID : unloadQueue) {
            // Not loaded is a SATISFIED request, the mirror of the load loop above: queueShipUnload
            // asks for a ship not to be loaded, and one that is already unloaded needs nothing done
            // to it. The state can arrive here legitimately — an unload queued on one tick for a ship
            // something else unloaded first, or a queue that outlived the world's own pass — and
            // dying for it is the same defect wearing the other sign.
            if (!loadedShips.containsKey(toUnloadID)) {
                continue;
            }
            PhysicsObject physicsObject = getPhysObjectFromUUID(toUnloadID);
            if (VSConfig.showAnnoyingDebugOutput) {
                System.out.println("Attempting to unload " + physicsObject);
            }
            physicsObject.unload();
            boolean success = loadedShips.remove(toUnloadID, physicsObject);
            if (!success) {
                throw new IllegalStateException("How did we fail to unload " + physicsObject.getShipData());
            }
            // The craft is still registered and still on disk - only the ship object is gone.
            noteUnloaded(physicsObject.getShipData());
        }
        unloadQueue.clear();
    }

    @Nonnull
    @Override
    public Iterable<PhysicsObject> getAllLoadedPhysObj() throws CalledFromWrongThreadException {
        enforceGameThread();
        return loadedShips.values();
    }

    @Nonnull
    @Override
    public ImmutableList<PhysicsObject> getAllLoadedThreadSafe() {
        return threadSafeLoadedShips;
    }

    /** Why the spawn queue would drop a ship instead of building it. */
    public enum SpawnRefusal {
        /** The search found more blocks than {@code VSConfig.maxDetectedShipSize}. */
        TOO_LARGE,
        /** The search touched bedrock, which no ship may take out of a world. */
        BEDROCK
    }

    /** The drain's detector parameters, in ONE place, because {@link #refusalFor} must ask the same question. */
    private static final boolean SPAWN_CHECKS_CORNERS = true;

    private static int spawnSizeLimit() {
        return VSConfig.maxDetectedShipSize + 1;
    }

    /** The drain's rule for dropping a ship, or {@code null} when it would build it. */
    @Nullable
    public static SpawnRefusal refusalOf(@Nonnull SpatialDetector detector) {
        if (detector.cleanHouse) {
            return SpawnRefusal.BEDROCK;
        }
        return detector.foundSet.size() > VSConfig.maxDetectedShipSize ? SpawnRefusal.TOO_LARGE : null;
    }

    /**
     * Would the spawn queue drop a ship queued with these arguments? Answered by running the same search
     * the drain runs, on the world as it stands now, and applying the same rule — so a caller can refuse
     * BEFORE queueing, where its player can be told why, instead of the drain dropping the ship a tick
     * later with a line on the error stream and nothing anyone sees.
     */
    @Nullable
    public SpawnRefusal refusalFor(@Nonnull BlockPos spawnPos, @Nonnull BlockFinder.BlockFinderType blockFinderType,
                                   @Nonnull StructureBoundingBox footprint) {
        return refusalOf(BlockFinder.getBlockFinderFor(blockFinderType, spawnPos, world, spawnSizeLimit(),
                SPAWN_CHECKS_CORNERS, footprint));
    }

    /**
     * Thread safe way to queue a ship spawn. (Not the same as {@link #queueShipLoad(UUID)}.
     *
     * <p>{@code cause} says WHY this ship is appearing — see {@link ShipLifecycleEvent.Cause}; it travels
     * with the queued spawn and is what the naming event carries when the queue is drained.</p>
     *
     * <p>{@code footprint} is the region the block search may not leave, inclusive: the blocks the
     * caller placed. It is required, with no unbounded form: the search used to stop only at the size
     * cap, so a craft took whatever touched it — a launch pad, through the snow on its rim, or a tree.</p>
     */
    public void queueShipSpawn(@Nonnull ShipData data, @Nonnull BlockPos spawnPos,
                               @Nonnull BlockFinder.BlockFinderType blockFinderType,
                               @Nonnull ShipLifecycleEvent.Cause cause,
                               @Nonnull StructureBoundingBox footprint) {
        enforceGameThread();
        this.spawnQueue.add(new QueuedSpawn(spawnPos, data, blockFinderType, cause, footprint));
    }

    /**
     * Is this ship in the manager's hands right now — loaded, queued to load, or streaming its chunks
     * in the background?
     *
     * <p>Anything about to DEREGISTER a ship has to ask THIS and not merely "is it loaded". A ship
     * whose chunks are being streamed has no {@link PhysicsObject} yet, so it answers "not loaded" to
     * {@link #getPhysObjectFromUUID(UUID)} while the loader is still holding its id; removing its
     * {@link ShipData} in that window throws {@code IllegalStateException} out of the world tick from
     * {@link #getHeldShipChunks()} on the very next chunk-provider tick, with nothing between
     * the throw and the server loop. The three queues below are the whole of "in the manager's
     * hands", and each of them dereferences its ids against the registry.</p>
     */
    public boolean isShipInUse(@Nonnull UUID shipID) {
        enforceGameThread();
        return loadedShips.containsKey(shipID)
            || loadQueue.contains(shipID)
            || backgroundLoadQueue.contains(shipID)
            || loadingInBackground.contains(shipID);
    }

    @Override
    public void queueShipLoad(@Nonnull UUID shipID) {
        enforceGameThread();
        this.loadQueue.add(shipID);
    }

    @Override
    public void queueShipUnload(@Nonnull UUID shipID) {
        enforceGameThread();
        this.unloadQueue.add(shipID);
    }

    /**
     * Thread safe way to queue a ship to be loaded in the background.
     */
    public void queueShipLoadBackground(@Nonnull UUID shipID) {
        enforceGameThread();
        backgroundLoadQueue.add(shipID);
    }

    /**
     * The chunks the world must not unload: the claim of every LOADED ship and of every ship loading
     * in the background.
     *
     * <p>A loaded ship's {@link PhysicsObject} keeps its own references to its claim's {@code Chunk}
     * objects and simulates from them, so a claim chunk the world drops while the ship lives splits
     * the ship in two — physics reads the dropped object, the world re-loads a new one from disk at
     * the next access, and the tiles in it stop ticking. Nothing else holds these chunks: a world
     * whose provider forbids respawning and which holds no player queues EVERY loaded chunk for
     * unload on every tick ({@code PlayerChunkMap#tick}), which is exactly a space slot with a
     * permanently loaded ship and nobody in it. A ship releases its chunks by unloading:
     * {@link PhysicsObject#unload} queues them, and the ship leaves {@code loadedShips} in the same
     * pass, so it is no longer named here on the provider's next tick.</p>
     */
    public Iterable<Long> getHeldShipChunks() throws CalledFromWrongThreadException {
        enforceGameThread();
        List<Long> held = new ArrayList<>();
        for (PhysicsObject ship : loadedShips.values()) {
            held.addAll(ship.getChunkClaim().getClaimedChunks());
        }
        QueryableShipData queryableShipData = QueryableShipData.get(world);
        for (UUID shipID : loadingInBackground) {
            Optional<ShipData> shipDataOptional = queryableShipData.getShip(shipID);
            if (!shipDataOptional.isPresent()) {
                throw new IllegalStateException("Ship data not present for:\n" + shipID);
            }
            held.addAll(shipDataOptional.get().getChunkClaim().getClaimedChunks());
        }
        return held;
    }

    @java.lang.SuppressWarnings("all")
    public WorldServer getWorld() {
        return this.world;
    }

    @java.lang.SuppressWarnings("all")
    public VSWorldPhysicsLoop getPhysicsLoop() {
        return this.physicsLoop;
    }
}
