// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.ships;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.ImmutableList;
import com.googlecode.cqengine.query.Query;
import com.googlecode.cqengine.resultset.ResultSet;
import mcp.MethodsReturnNonnullByDefault;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.ChunkPos;
import net.minecraft.world.World;
import org.valkyrienskies.mod.common.config.VSConfig;
import org.valkyrienskies.mod.common.ships.interpolation.ITransformInterpolator;
import org.valkyrienskies.mod.common.ships.ship_world.IPhysObjectWorld;
import org.valkyrienskies.mod.common.ships.ship_world.PhysicsObject;
import org.valkyrienskies.mod.common.util.ValkyrienUtils;
import org.valkyrienskies.mod.common.util.cqengine.ConcurrentUpdatableIndexedCollection;
import org.valkyrienskies.mod.common.util.cqengine.UpdatableHashIndex;
import org.valkyrienskies.mod.common.util.cqengine.UpdatableUniqueIndex;
import java.lang.reflect.Field;
import java.util.*;
import java.util.function.BiConsumer;
import java.util.stream.Stream;
import static com.googlecode.cqengine.query.QueryFactory.equal;

/**
 * A class that keeps track of ship data
 */
@MethodsReturnNonnullByDefault
@SuppressWarnings("WeakerAccess")
public class QueryableShipData implements Iterable<ShipData> {
    @java.lang.SuppressWarnings("all")
    private static final org.apache.logging.log4j.Logger log = org.apache.logging.log4j.LogManager.getLogger(QueryableShipData.class);
    // Where every ship data instance is stored, regardless if the corresponding PhysicsObject is
    // loaded in the World or not.
    private ConcurrentUpdatableIndexedCollection<ShipData> allShips;

    public QueryableShipData() {
        this(new ConcurrentUpdatableIndexedCollection<>());
    }

    // This tells Jackson to pass in allShips when serializing
    // The default thing that is passed in will be 'null' if none exists
    @JsonCreator
    public QueryableShipData(@JsonProperty("allShips") ConcurrentUpdatableIndexedCollection<ShipData> ships) {
        if (ships == null) {
            ships = new ConcurrentUpdatableIndexedCollection<>();
        }
        this.allShips = ships;
        // For every ship data, set the 'owner' field to us -- kinda hacky but what can I do
        // I don't want to serialize a billion references to this
        // This probably only needs to be done once per world, so this is fine
        this.allShips.forEach(data -> {
            try {
                Field owner = ShipData.class.getDeclaredField("owner");
                owner.setAccessible(true);
                owner.set(data, this.allShips);
            } catch (NoSuchFieldException | IllegalAccessException e) {
                e.printStackTrace();
                throw new RuntimeException(e);
            }
        });
        this.allShips.addIndex(UpdatableHashIndex.onAttribute(ShipData.NAME));
        this.allShips.addIndex(UpdatableUniqueIndex.onAttribute(ShipData.UUID));
        // HASH, not UNIQUE: null is the ordinary value here (every craft Stellurgy does not
        // own), and this index exists so translating its durable id into a ship is a probe rather than
        // a walk over every registered ship.
        this.allShips.addIndex(UpdatableHashIndex.onAttribute(ShipData.AR_DURABLE_ID));
        this.allShips.addIndex(UpdatableUniqueIndex.onAttribute(ShipData.CHUNKS));
    }

    /**
     * @see ValkyrienUtils#getQueryableData(World)
     */
    public static QueryableShipData get(World world) {
        return ValkyrienUtils.getQueryableData(world);
    }

    /**
     * @deprecated Do not use -- thinking of better API choices
     */
    @Deprecated
    public ConcurrentUpdatableIndexedCollection<ShipData> getAllShips() {
        return allShips;
    }

    /**
     * Retrieves a list of all ships.
     */
    public List<ShipData> getShips() {
        return ImmutableList.copyOf(allShips);
    }

    public Optional<ShipData> getShipFromChunk(int chunkX, int chunkZ) {
        return getShipFromChunk(ChunkPos.asLong(chunkX, chunkZ));
    }

    public Optional<ShipData> getShipFromBlock(BlockPos pos) {
        return getShipFromChunk(pos.getX() >> 4, pos.getZ() >> 4);
    }

    public Optional<ShipData> getShipFromChunk(long chunkLong) {
        Query<ShipData> query = equal(ShipData.CHUNKS, chunkLong);
        try (ResultSet<ShipData> resultSet = allShips.retrieve(query)) {
            if (resultSet.size() > 1) {
                throw new IllegalStateException("How the heck did we get 2 or more ships both managing the chunk at " + chunkLong);
            }
            if (resultSet.isEmpty()) {
                return Optional.empty();
            } else {
                return Optional.of(resultSet.uniqueResult());
            }
        }
    }

    public Optional<ShipData> getShip(UUID uuid) {
        Query<ShipData> query = equal(ShipData.UUID, uuid);
        try (ResultSet<ShipData> resultSet = allShips.retrieve(query)) {
            if (resultSet.isEmpty()) {
                return Optional.empty();
            } else {
                return Optional.of(resultSet.uniqueResult());
            }
        }
    }

    /**
     * The ship carrying Stellurgy's DURABLE id {@code stellurgyDurableId}, or empty.
     *
     * <p>Indexed like {@link #getShip(UUID)} rather than searched: Stellurgy keys its transits, its ledger
     * and its aboard tags by an id its flight computer persists, this mod keys everything by
     * {@link ShipData#getUuid()}, and a caller holding the first one used to have to fall back to
     * asking which ship is NEAREST a point. That is exact until the world holds a second craft and
     * silently wrong afterwards, so the translation has to be cheap enough that nobody is tempted.</p>
     *
     * <p>Not unique-indexed on purpose: {@code null} is the ordinary value for every craft Stellurgy does not
     * own, and a unique index over a mostly-null attribute is a trap. Two ships genuinely sharing a
     * durable id would be a bug in whoever bound them, and is reported rather than thrown.</p>
     */
    public Optional<ShipData> getShipFromStellurgyDurableId(UUID stellurgyDurableId) {
        if (stellurgyDurableId == null) {
            return Optional.empty();
        }
        Query<ShipData> query = equal(ShipData.AR_DURABLE_ID, stellurgyDurableId);
        try (ResultSet<ShipData> resultSet = allShips.retrieve(query)) {
            if (resultSet.isEmpty()) {
                return Optional.empty();
            }
            if (resultSet.size() > 1) {
                log.error("Two or more ships claim the same Stellurgy durable id {} - refusing "
                    + "to guess which one a caller meant. Whoever bound the second one has a bug.", stellurgyDurableId);
                return Optional.empty();
            }
            return Optional.of(resultSet.uniqueResult());
        }
    }

    public Optional<ShipData> getShipFromName(String name) {
        Query<ShipData> query = equal(ShipData.NAME, name);
        try (ResultSet<ShipData> shipDataResultSet = allShips.retrieve(query)) {
            if (shipDataResultSet.isEmpty()) {
                return Optional.empty();
            } else {
                return Optional.of(shipDataResultSet.uniqueResult());
            }
        }
    }

    public void removeShip(UUID uuid) {
        getShip(uuid).ifPresent(ship -> allShips.remove(ship));
    }

    public void removeShip(ShipData data) {
        allShips.remove(data);
    }

    public void addShip(ShipData ship) {
        if (VSConfig.showAnnoyingDebugOutput) {
            System.out.println(ship.getName());
        }
        allShips.add(ship);
    }

    /**
     * Adds the ShipData if it doesn't exist, or updates the values of the old ShipData to match the input.
     *
     * @return reference to the "real" ShipData object used by {@link IPhysObjectWorld} and {@link PhysicsObject}.
     */
    public ShipData addOrUpdateShipPreservingPhysObj(ShipData ship, World world) {
        Optional<ShipData> old = getShip(ship.getUuid());
        if (old.isPresent()) {
            PhysicsObject physicsObject = ValkyrienUtils.getPhysObjWorld(world).getPhysObjectFromUUID(ship.getUuid());
            if (physicsObject != null) {
            } else 
            // Ship transform updates are now done by ShipTransformUpdateMessageHandler
            // ITransformInterpolator interpolator = physicsObject.getTransformInterpolator();
            // interpolator.onNewTransformPacket(ship.getShipTransform(), ship.getShipBB());
            {
                old.get().setShipTransform(ship.getShipTransform());
                old.get().setPrevTickShipTransform(ship.getPrevTickShipTransform());
                old.get().setShipBB(ship.getShipBB());
            }
            // old.get().setName(ship.getName());
            old.get().setPhysicsEnabled(ship.isPhysicsEnabled());
            // Update inertia data
            old.get().getInertiaData().setGameMoITensor(ship.getInertiaData().getGameMoITensor());
            old.get().getInertiaData().setGameTickMass(ship.getInertiaData().getGameTickMass());
            old.get().getInertiaData().setGameTickCenterOfMass(ship.getInertiaData().getGameTickCenterOfMass());
            return old.get();
        } else {
            this.allShips.add(ship);
            return ship;
        }
    }

    public void registerUpdateListener(BiConsumer<Iterable<ShipData>, Iterable<ShipData>> updateListener) {
        allShips.registerUpdateListener(updateListener);
    }

    /**
     * Atomically updates ShipData. It must be true that <code>!oldData.equals(newData)</code>
     *
     * @param oldData The old data object(s) to replace
     * @param newData The new data object(s)
     */
    public void updateShipData(Iterable<ShipData> oldData, Iterable<ShipData> newData) {
        this.allShips.update(oldData, newData);
    }

    /**
     * Atomically updates ShipData. It must be true that <code>!oldData.equals(newData)</code>
     *
     * @param oldData The old data object to replace
     * @param newData The new data object
     */
    public void updateShipData(ShipData oldData, ShipData newData) {
        this.updateShipData(Collections.singleton(oldData), Collections.singleton(newData));
    }

    @Override
    public Iterator<ShipData> iterator() {
        return allShips.iterator();
    }

    public Stream<ShipData> stream() {
        return allShips.stream();
    }
}
