// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.ships;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.googlecode.cqengine.attribute.Attribute;
import com.googlecode.cqengine.attribute.MultiValueAttribute;
import com.googlecode.cqengine.query.option.QueryOptions;
import net.minecraft.util.math.AxisAlignedBB;
import org.joml.Vector3d;
import org.valkyrienskies.mod.common.ships.chunk_claims.VSChunkClaim;
import org.valkyrienskies.mod.common.ships.physics_data.ShipInertiaData;
import org.valkyrienskies.mod.common.ships.physics_data.ShipPhysicsData;
import org.valkyrienskies.mod.common.ships.ship_transform.ShipTransform;
import org.valkyrienskies.mod.common.ships.ship_world.IPhysObjectWorld;
import org.valkyrienskies.mod.common.util.cqengine.ConcurrentUpdatableIndexedCollection;
import org.valkyrienskies.mod.common.util.datastructures.IBlockPosSet;
import org.valkyrienskies.mod.common.util.datastructures.IBlockPosSetAABB;
import org.valkyrienskies.mod.common.util.datastructures.SmallBlockPosSet;
import org.valkyrienskies.mod.common.util.datastructures.SmallBlockPosSetAABB;
import org.valkyrienskies.mod.common.util.jackson.annotations.PacketIgnore;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.util.Set;
import java.util.UUID;
import static com.googlecode.cqengine.query.QueryFactory.attribute;
import static com.googlecode.cqengine.query.QueryFactory.nullableAttribute;
// For Jackson
/**
 * One of these objects will represent a ship. You can obtain a physics object for that ship (if one
 * is available), by calling {@link IPhysObjectWorld#getPhysObjectFromUUID(UUID)}.
 */
public class ShipData {
    /**
     * The {@link QueryableShipData} that manages this
     */
    private final transient ConcurrentUpdatableIndexedCollection<ShipData> owner;
    // region Data Fields
    /**
     * Physics information -- mutable but final. References to this <strong>should be guaranteed to
     * never change</strong> for the duration of a game.
     */
    private final ShipPhysicsData physicsData;
    private final ShipInertiaData inertiaData;
    /**
     * Do not use this for anything client side! Contains all of the non-air block positions on the ship.
     * This is used for generating AABBs and deconstructing the ship.
     */
    @PacketIgnore
    @Nullable
    @JsonSerialize(as = SmallBlockPosSetAABB.class)
    @JsonDeserialize(as = SmallBlockPosSetAABB.class)
    public IBlockPosSetAABB blockPositions;
    /**
     * Do not use this for anything client side! Contains all the positions of force producing blocks on the ship.
     */
    @PacketIgnore
    @Nullable
    @JsonSerialize(as = SmallBlockPosSet.class)
    @JsonDeserialize(as = SmallBlockPosSet.class)
    public IBlockPosSet activeForcePositions;
    private ShipTransform shipTransform;
    private ShipTransform prevTickShipTransform;
    private AxisAlignedBB shipBB;
    /**
     * Whether or not physics are enabled on this physo
     */
    private boolean physicsEnabled;
    /**
     * The chunks claimed by this physo
     */
    private final VSChunkClaim chunkClaim;
    /**
     * This ships UUID
     */
    private final UUID uuid;
    /**
     * The (unique) name of the physo as displayed to players
     */
    private String name;
    /**
     * This ship is DEAD: it is to be collected on the next tick of the world that carries it,
     * whether or not it is loaded.
     *
     * <p><b>Why the flag lives here and not on the physics object.</b> A ship's disposal was decided
     * by {@code PhysicsObject.shouldShipBeDestroyed()}, and the destroy pass asks it only of the
     * LOADED ships — so a craft nobody had loaded could not be collected by the substrate at all, and
     * every caller that emptied one had to reach in and deregister it by hand. A record exists loaded
     * or not, which is the only place a disposal decision can be made once and then honoured.</p>
     *
     * <p><b>Transient on purpose.</b> Death is a decision about the next tick, not a property of the
     * craft worth persisting: a save taken between the mark and the collection restores a ship whose
     * block set is empty, and an empty block set already answers {@code shouldShipBeDestroyed} on its
     * own. Writing it out would also make a corrupted or hand-edited save able to delete a live
     * ship.</p>
     */
    private transient boolean dead;
    /**
     * Advanced Rocketry's DURABLE ship id for this craft, or {@code null} for a craft AR does not
     * own.
     *
     * <p>AR carries a second identity for a tier-2 ship: an id minted and persisted by its flight
     * computer, chosen because it survives a re-assembly and therefore names the same vessel across
     * a crossing, a restart and a re-registration under a fresh {@link #uuid}. Its transit records,
     * its durable ledger and its aboard tags are all keyed by it, while everything in this mod is
     * keyed by {@code uuid} — two spaces with no crossing, so a caller holding one of them had to
     * fall back to asking WHICH SHIP IS NEAREST a point, which is exact until a cell holds a second
     * craft (or a blockless remnant of one) and silently wrong afterwards.</p>
     *
     * <p>Kept HERE, beside the uuid and indexed with it, so that translation is one hash probe rather
     * than a walk over every registered ship asking each for its computer. Set through
     * {@link #setArDurableId} so the index is updated with the field.</p>
     */
    @Nullable
    private UUID arDurableId;

    // endregion
    private ShipData( ConcurrentUpdatableIndexedCollection<ShipData> owner, ShipPhysicsData physicsData, @Nonnull ShipInertiaData inertiaData,  ShipTransform shipTransform,  ShipTransform prevTickShipTransform,  AxisAlignedBB shipBB, boolean physicsEnabled,  VSChunkClaim chunkClaim,  UUID uuid,  String name) {
        if (owner == null) {
            throw new java.lang.NullPointerException("owner is marked non-null but is null");
        }
        if (shipTransform == null) {
            throw new java.lang.NullPointerException("shipTransform is marked non-null but is null");
        }
        if (prevTickShipTransform == null) {
            throw new java.lang.NullPointerException("prevTickShipTransform is marked non-null but is null");
        }
        if (shipBB == null) {
            throw new java.lang.NullPointerException("shipBB is marked non-null but is null");
        }
        if (chunkClaim == null) {
            throw new java.lang.NullPointerException("chunkClaim is marked non-null but is null");
        }
        if (uuid == null) {
            throw new java.lang.NullPointerException("uuid is marked non-null but is null");
        }
        if (name == null) {
            throw new java.lang.NullPointerException("name is marked non-null but is null");
        }
        this.owner = owner;
        this.physicsData = physicsData;
        this.inertiaData = inertiaData;
        this.shipTransform = shipTransform;
        this.prevTickShipTransform = prevTickShipTransform;
        this.shipBB = shipBB;
        this.physicsEnabled = physicsEnabled;
        this.chunkClaim = chunkClaim;
        this.uuid = uuid;
        this.name = name;
        this.blockPositions = new SmallBlockPosSetAABB(chunkClaim.getCenterPos().getXStart(), 0, chunkClaim.getCenterPos().getZStart(), 1024, 1024, 1024);
        this.activeForcePositions = new SmallBlockPosSet(chunkClaim.getCenterPos().getXStart(), chunkClaim.getCenterPos().getZStart());
    }

    public static ShipData createData(ConcurrentUpdatableIndexedCollection<ShipData> owner, String name, VSChunkClaim chunkClaim, UUID shipID, ShipTransform shipTransform, AxisAlignedBB aabb) {
        return new ShipData(owner, new ShipPhysicsData(new Vector3d(), new Vector3d()), new ShipInertiaData(), shipTransform, shipTransform, aabb, false, chunkClaim, shipID, name);
    }

    // region Setters
    public ShipData setName(String name) {
        this.name = name;
        owner.updateObjectIndices(this, NAME);
        return this;
    }

    /**
     * Bind (or clear) Advanced Rocketry's durable id for this craft — see {@link #arDurableId}.
     *
     * <p>Goes through the index the same way {@link #setName} does: a field written behind the
     * collection's back leaves the index answering with the OLD value, which for an identity lookup
     * means confidently naming the wrong ship.</p>
     */
    public ShipData setArDurableId(@Nullable UUID arDurableId) {
        this.arDurableId = arDurableId;
        owner.updateObjectIndices(this, AR_DURABLE_ID);
        return this;
    }

    /**
     * The same binding for a record that is NOT IN THE COLLECTION YET — a ship built or re-assembled
     * but not yet spawned. The index is not touched, because there is nothing to update: the record
     * is indexed on every attribute when it is added, so the name set here is carried in with it.
     *
     * <p>The distinction is not cosmetic. {@link #setArDurableId}'s index update inserts the object
     * into the store as a side effect, so using it here would register the ship BEFORE its blocks
     * exist — briefly answering position and identity lookups for a craft that is not there yet.</p>
     */
    public ShipData setArDurableIdBeforeRegistration(@Nullable UUID arDurableId) {
        this.arDurableId = arDurableId;
        return this;
    }

    // endregion
    // region Attributes
    public static final Attribute<ShipData, String> NAME = nullableAttribute(ShipData::getName);
    public static final Attribute<ShipData, UUID> UUID = attribute(ShipData::getUuid);
    /** {@link #arDurableId}, nullable because most craft carry none. */
    public static final Attribute<ShipData, UUID> AR_DURABLE_ID =
        nullableAttribute(ShipData::getArDurableId);
    public static final Attribute<ShipData, Long> CHUNKS = new MultiValueAttribute<ShipData, Long>() {
        @Override
        public Set<Long> getValues(ShipData physo, QueryOptions queryOptions) {
            return physo.getChunkClaim().getClaimedChunks();
        }
    };

    /**
     * Physics information -- mutable but final. References to this <strong>should be guaranteed to
     * never change</strong> for the duration of a game.
     */
    @java.lang.SuppressWarnings("all")
    public ShipPhysicsData getPhysicsData() {
        return this.physicsData;
    }

    @java.lang.SuppressWarnings("all")
    public ShipInertiaData getInertiaData() {
        return this.inertiaData;
    }

    /**
     * Do not use this for anything client side! Contains all of the non-air block positions on the ship.
     * This is used for generating AABBs and deconstructing the ship.
     */
    @Nullable
    @java.lang.SuppressWarnings("all")
    public IBlockPosSetAABB getBlockPositions() {
        return this.blockPositions;
    }

    /**
     * Do not use this for anything client side! Contains all the positions of force producing blocks on the ship.
     */
    @Nullable
    @java.lang.SuppressWarnings("all")
    public IBlockPosSet getActiveForcePositions() {
        return this.activeForcePositions;
    }

    @java.lang.SuppressWarnings("all")
    public ShipTransform getShipTransform() {
        return this.shipTransform;
    }

    @java.lang.SuppressWarnings("all")
    public ShipTransform getPrevTickShipTransform() {
        return this.prevTickShipTransform;
    }

    @java.lang.SuppressWarnings("all")
    public AxisAlignedBB getShipBB() {
        return this.shipBB;
    }

    /**
     * Whether or not physics are enabled on this physo
     */
    @java.lang.SuppressWarnings("all")
    public boolean isPhysicsEnabled() {
        return this.physicsEnabled;
    }

    /**
     * The chunks claimed by this physo
     */
    @java.lang.SuppressWarnings("all")
    public VSChunkClaim getChunkClaim() {
        return this.chunkClaim;
    }

    /**
     * This ships UUID
     */
    @java.lang.SuppressWarnings("all")
    public UUID getUuid() {
        return this.uuid;
    }

    /** Whether this ship has been marked for collection — see {@link #dead}. */
    public boolean isDead() {
        return this.dead;
    }

    /**
     * Mark this ship for collection on the next tick of its world.
     *
     * <p>The caller says the craft is finished; WHEN and HOW it leaves the registry stays the
     * substrate's business, which is the point — a caller that deregistered by hand had to know the
     * substrate's own ordering (that a blockless ship is collected by a pass which copies nothing
     * back, and that removing the record first makes the load/unload pass iterate a collection the
     * entry is already out of, so it never sees it again). Marking states the intent and leaves the
     * ordering where it is understood.</p>
     *
     * <p>Idempotent, and never un-set: nothing revives a ship somebody declared finished.</p>
     */
    public void markDead() {
        this.dead = true;
    }

    /**
     * The (unique) name of the physo as displayed to players
     */
    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    /** Advanced Rocketry's durable id for this craft, or {@code null}. See {@link #arDurableId}. */
    @Nullable
    public UUID getArDurableId() {
        return this.arDurableId;
    }

    @java.lang.SuppressWarnings("all")
    private ShipData() {
        this.owner = null;
        this.physicsData = null;
        this.inertiaData = null;
        this.chunkClaim = null;
        this.uuid = null;
    }

    @java.lang.SuppressWarnings("all")
    public void setShipTransform(final ShipTransform shipTransform) {
        this.shipTransform = shipTransform;
    }

    @java.lang.SuppressWarnings("all")
    public void setPrevTickShipTransform(final ShipTransform prevTickShipTransform) {
        this.prevTickShipTransform = prevTickShipTransform;
    }

    @java.lang.SuppressWarnings("all")
    public void setShipBB(final AxisAlignedBB shipBB) {
        this.shipBB = shipBB;
    }

    /**
     * Whether or not physics are enabled on this physo
     */
    @java.lang.SuppressWarnings("all")
    public void setPhysicsEnabled(final boolean physicsEnabled) {
        this.physicsEnabled = physicsEnabled;
    }
    // endregion
}
