// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.capability.framework;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.util.function.Supplier;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;
import net.minecraft.nbt.NBTBase;
import net.minecraft.nbt.NBTTagByteArray;
import net.minecraft.util.EnumFacing;
import org.valkyrienskies.mod.common.capability.VSWorldDataCapability;
import org.valkyrienskies.mod.common.util.jackson.VSJacksonUtil;

/**
 * Implement as follows
 *
 * <pre>{@code
 * public class VSWorldDataCapability extends VSDefaultCapability<VSWorldData> {
 *     public VSWorldDataCapability(ObjectMapper mapper) {
 *         super(VSWorldData.class, VSWorldData::new, mapper);
 *     }
 *
 *     public VSWorldDataCapability() {
 *         super(VSWorldData.class, VSWorldData::new);
 *     }
 * }
 * }</pre>
 *
 * @param <K> The type of object this capability should store
 * @see VSWorldDataCapability
 */
@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
public abstract class VSDefaultCapability<K> {
    /** Effectively final, process lifetime: built once at class initialisation. */
    @java.lang.SuppressWarnings("all")
    private static final org.apache.logging.log4j.Logger log = org.apache.logging.log4j.LogManager.getLogger(VSDefaultCapability.class);
    private final ObjectMapper mapper;
    private final Class<K> kClass;
    @Nonnull
    private K instance;
    private Supplier<K> factory;
    /**
     * The world this capability was attached to, purely so the save/load log lines can say WHICH
     * world they belong to. A serialisation line that reports only a size and a class name cannot be
     * attributed to a dimension, so "one big payload and several empty ones" is unreadable the moment
     * a save holds more than one world with ships in it.
     */
    @Nullable
    private net.minecraft.world.World owner;

    public VSDefaultCapability(Class<K> kClass, Supplier<K> factory) {
        this(kClass, factory, VSJacksonUtil.getDefaultMapper());
    }

    public VSDefaultCapability(Class<K> kClass, Supplier<K> factory, ObjectMapper mapper) {
        this.kClass = kClass;
        this.factory = factory;
        this.instance = factory.get();
        log.debug("CONSTRUCTED INSTANCE: " + instance);
        this.mapper = mapper;
    }

    /** Remember which world owns this capability, for the save/load log lines. */
    public void setOwner(@Nullable net.minecraft.world.World owner) {
        this.owner = owner;
    }

    /** {@code dim<N>/server|client}, or {@code ?} when this capability was attached without a world. */
    private String ownerName() {
        if (owner == null) {
            return "?";
        }
        return "dim" + owner.provider.getDimension() + (owner.isRemote ? "/client" : "/server");
    }

    /**
     * What the payload CONTAINS, beside how big it is. Overridden where the stored object has a
     * meaningful population count; a size alone cannot distinguish "this world has nothing in it"
     * from "this world's contents were dropped before the save".
     */
    protected String describe(K instance) {
        return instance.getClass().getSimpleName();
    }

    @Nullable
    public NBTTagByteArray writeNBT(EnumFacing side) {
        long time = System.currentTimeMillis();
        byte[] value;
        try {
            value = getMapper().writeValueAsBytes(instance);
            log.debug("VS serialization took {} ms. Writing data of size {} KB. ({} {} inst@{})", System.currentTimeMillis() - time, value.length / Math.pow(2, 10), ownerName(), describe(instance), Integer.toHexString(System.identityHashCode(instance)));
        } catch (Exception ex) {
            log.fatal("Something just broke horrifically. Be wary of your data. This will crash the game in future releases", ex);
            value = new byte[0];
        }
        return new NBTTagByteArray(value);
    }

    public K readNBT(NBTBase base, EnumFacing side) {
        long time = System.currentTimeMillis();
        try {
            byte[] value = ((NBTTagByteArray) base).getByteArray();
            this.instance = mapper.readValue(value, kClass);
            log.info("VS deserialization took {} ms. Reading data of size {} KB. ({} {} inst@{})", System.currentTimeMillis() - time, value.length / Math.pow(2, 10), ownerName(), describe(this.instance), Integer.toHexString(System.identityHashCode(this.instance)));
        } catch (IOException | ClassCastException ex) {
            log.fatal("Failed to read your ship data? Ships will probably be missing", ex);
            this.instance = factory.get();
        }
        // Possibly redundant null check. TODO: remove
        if (this.instance == null) {
            log.fatal("Failed to read your ship data? Ships will probably be missing");
            this.instance = factory.get();
        }
        return this.instance;
    }

    public K get() {
        return instance;
    }

    public void set(K instance) {
        this.instance = instance;
    }

    @java.lang.SuppressWarnings("all")
    protected ObjectMapper getMapper() {
        return this.mapper;
    }
}
