// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.ships.ship_transform;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import net.minecraft.entity.Entity;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.Vec3d;
import org.joml.*;
import org.valkyrienskies.mod.common.util.JOML;
import org.valkyrienskies.mod.common.util.ValkyrienNBTUtils;
import org.valkyrienskies.mod.common.util.ValkyrienUtils;
import valkyrienwarfare.api.TransformType;
import javax.annotation.concurrent.Immutable;

/**
 * Immutable wrapper around the rotation matrices used by ships. The immutability is extremely
 * important to enforce for preventing multi-threaded access issues. All access to the internal
 * arrays is blocked to guarantee nothing goes wrong.
 * <p>
 * Used to transform vectors between the global coordinate system, and the subspace (ship)
 * coordinate system. TODO: Move this to VS API.
 *
 * @author thebest108
 */
@Immutable
public class ShipTransform {
    /** Effectively final, process lifetime: built once at class initialisation. */
    @java.lang.SuppressWarnings("all")
    private static final org.apache.logging.log4j.Logger log = org.apache.logging.log4j.LogManager.getLogger(ShipTransform.class);
    /**
     * A transformation matrix used to convert 'subspace' coordinates into 'global' coordinates.
     */
    @JsonDeserialize(as = Matrix4d.class)
    private final Matrix4dc subspaceToGlobal;
    /**
     * A transformation matrix used to convert 'global' coordinates into 'subspace coordinates'
     */
    @JsonDeserialize(as = Matrix4d.class)
    private final Matrix4dc globalToSubspace;
    private final double posX;
    private final double posY;
    private final double posZ;
    private final Vector3dc centerCoord;

    public ShipTransform(Vector3dc position, Vector3dc centerCoord) {
        this(position.x(), position.y(), position.z(), new Quaterniond(), centerCoord);
    }

    public ShipTransform(Vector3dc position, Quaterniondc rotation, Vector3dc centerCoord) {
        this(position.x(), position.y(), position.z(), rotation, centerCoord);
    }

    public ShipTransform(double posX, double posY, double posZ, Quaterniondc rotation, Vector3dc centerCoord) {
        this.posX = posX;
        this.posY = posY;
        this.posZ = posZ;
        this.centerCoord = centerCoord;
        this.subspaceToGlobal = 
        // Finally we translate the coordinates to where they are in the world.
        // Then we rotate about the coordinate origin based on the pitch/yaw/roll.
        // First translate the block coordinates to coordinates where center of mass is <0,0,0>
        // E.g., move the coordinate origin to <0,0,0>
        new Matrix4d().translate(posX, posY, posZ).rotate(rotation).translate(-centerCoord.x(), -centerCoord.y(), -centerCoord.z());
        this.globalToSubspace = subspaceToGlobal.invert(new Matrix4d());
    }

    public BlockPos getShipPositionBlockPos() {
        return new BlockPos(this.getPosX(), this.getPosY(), this.getPosZ());
    }

    public Vec3d getShipPositionVec3d() {
        return new Vec3d(this.getPosX(), this.getPosY(), this.getPosZ());
    }

    public static Matrix4d createTransform(ShipTransform prev, ShipTransform current) {
        return current.subspaceToGlobal.mul(prev.globalToSubspace, new Matrix4d());
    }

    /**
     * Better than {@link #transformPosition(Vector3d, TransformType)}
     */
    public Vector3d transformPositionNew(Vector3d position, TransformType transformType) {
        return getTransformMatrix(transformType).transformPosition(position);
    }

    /**
     * Better than {@link #transformDirection(Vector3d, TransformType)}
     */
    public Vector3d transformDirectionNew(Vector3d direction, TransformType transformType) {
        return getTransformMatrix(transformType).transformDirection(direction);
    }

    public void transformPosition(Vector3d position, TransformType transformType) {
        getTransformMatrix(transformType).transformPosition(position);
    }

    public void transformDirection(Vector3d direction, TransformType transformType) {
        getTransformMatrix(transformType).transformDirection(direction);
    }

    public Vec3d transform(Vec3d vec3d, TransformType transformType) {
        Vector3d vec3dAsVector = JOML.convert(vec3d);
        transformPosition(vec3dAsVector, transformType);
        return JOML.toMinecraft(vec3dAsVector);
    }

    public Vec3d rotate(Vec3d vec3d, TransformType transformType) {
        Vector3d vec3dAsVector = new Vector3d(vec3d.x, vec3d.y, vec3d.z);
        transformDirection(vec3dAsVector, transformType);
        return new Vec3d(vec3dAsVector.x, vec3dAsVector.y, vec3dAsVector.z);
    }

    public BlockPos transform(BlockPos pos, TransformType transformType) {
        Vector3d blockPosAsVector = new Vector3d(pos.getX() + 0.5, pos.getY() + 0.5, pos.getZ() + 0.5);
        transformPosition(blockPosAsVector, transformType);
        return new BlockPos(blockPosAsVector.x - 0.5, blockPosAsVector.y - 0.5, blockPosAsVector.z - 0.5);
    }

    public Quaterniond rotationQuaternion(TransformType transformType) {
        return getTransformMatrix(transformType).getNormalizedRotation(new Quaterniond());
    }

    public void writeToNBT(NBTTagCompound compound, String name) {
        compound.setByteArray(name, ValkyrienNBTUtils.toByteArray(subspaceToGlobal.get(new double[16])));
    }

    /**
     * Creates a standard 3x3 rotation matrix for this transform and the given transform type.
     */
    public Matrix3dc createRotationMatrix(TransformType transformType) {
        return getTransformMatrix(transformType).get3x3(new Matrix3d());
    }

    /**
     * Returns the same matrix this object has (not a copy). For that reason please <h1>DO NOT CAST
     * THIS</h1> to Matrix4d. Doing so would violate the contract that the internal transform never
     * changes, so DO NOT DO IT! You would be worse than Thanos! You wouldn't break half the mod,
     * you would break EVERYTHING. Your computer would explode, your house would burn down, your dog
     * will die, you'll be exiled from your home country, and your parents will disown you. Even if
     * you so much as think about casting this back to a Matrix4d you'll likely get struck by an
     * asteroid. You've been warned.
     *
     * @deprecated use {@link #getSubspaceToGlobal()} and {@link #getGlobalToSubspace()} instead
     */
    @Deprecated
    public Matrix4dc getTransformMatrix(TransformType transformType) {
        switch (transformType) {
        case SUBSPACE_TO_GLOBAL: 
            return subspaceToGlobal;
        case GLOBAL_TO_SUBSPACE: 
            return globalToSubspace;
        default: 
            throw new IllegalArgumentException("Unexpected TransformType Enum: " + transformType);
        }
    }

    public void transform(final Entity player, final TransformType globalToSubspace, final boolean transformEntityBoundingBox) {
        ValkyrienUtils.transformEntity(getTransformMatrix(globalToSubspace), player, transformEntityBoundingBox);
    }


    @java.lang.SuppressWarnings("all")
    public static class ShipTransformBuilder {
        @java.lang.SuppressWarnings("all")
        private Matrix4dc subspaceToGlobal;
        @java.lang.SuppressWarnings("all")
        private Matrix4dc globalToSubspace;
        @java.lang.SuppressWarnings("all")
        private double posX;
        @java.lang.SuppressWarnings("all")
        private double posY;
        @java.lang.SuppressWarnings("all")
        private double posZ;
        @java.lang.SuppressWarnings("all")
        private Vector3dc centerCoord;

        @java.lang.SuppressWarnings("all")
        ShipTransformBuilder() {
        }

        /**
         * A transformation matrix used to convert 'subspace' coordinates into 'global' coordinates.
         */
        @java.lang.SuppressWarnings("all")
        public ShipTransformBuilder subspaceToGlobal(final Matrix4dc subspaceToGlobal) {
            this.subspaceToGlobal = subspaceToGlobal;
            return this;
        }

        /**
         * A transformation matrix used to convert 'global' coordinates into 'subspace coordinates'
         */
        @java.lang.SuppressWarnings("all")
        public ShipTransformBuilder globalToSubspace(final Matrix4dc globalToSubspace) {
            this.globalToSubspace = globalToSubspace;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public ShipTransformBuilder posX(final double posX) {
            this.posX = posX;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public ShipTransformBuilder posY(final double posY) {
            this.posY = posY;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public ShipTransformBuilder posZ(final double posZ) {
            this.posZ = posZ;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public ShipTransformBuilder centerCoord(final Vector3dc centerCoord) {
            this.centerCoord = centerCoord;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public ShipTransform build() {
            return new ShipTransform(subspaceToGlobal, globalToSubspace, posX, posY, posZ, centerCoord);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ShipTransform.ShipTransformBuilder(subspaceToGlobal=" + this.subspaceToGlobal + ", globalToSubspace=" + this.globalToSubspace + ", posX=" + this.posX + ", posY=" + this.posY + ", posZ=" + this.posZ + ", centerCoord=" + this.centerCoord + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static ShipTransformBuilder builder() {
        return new ShipTransformBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public ShipTransformBuilder toBuilder() {
        return new ShipTransformBuilder().subspaceToGlobal(this.subspaceToGlobal).globalToSubspace(this.globalToSubspace).posX(this.posX).posY(this.posY).posZ(this.posZ).centerCoord(this.centerCoord);
    }

    /**
     * A transformation matrix used to convert 'subspace' coordinates into 'global' coordinates.
     */
    @java.lang.SuppressWarnings("all")
    public Matrix4dc getSubspaceToGlobal() {
        return this.subspaceToGlobal;
    }

    /**
     * A transformation matrix used to convert 'global' coordinates into 'subspace coordinates'
     */
    @java.lang.SuppressWarnings("all")
    public Matrix4dc getGlobalToSubspace() {
        return this.globalToSubspace;
    }

    @java.lang.SuppressWarnings("all")
    public double getPosX() {
        return this.posX;
    }

    @java.lang.SuppressWarnings("all")
    public double getPosY() {
        return this.posY;
    }

    @java.lang.SuppressWarnings("all")
    public double getPosZ() {
        return this.posZ;
    }

    @java.lang.SuppressWarnings("all")
    public Vector3dc getCenterCoord() {
        return this.centerCoord;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ShipTransform)) return false;
        final ShipTransform other = (ShipTransform) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$subspaceToGlobal = this.getSubspaceToGlobal();
        final java.lang.Object other$subspaceToGlobal = other.getSubspaceToGlobal();
        if (this$subspaceToGlobal == null ? other$subspaceToGlobal != null : !this$subspaceToGlobal.equals(other$subspaceToGlobal)) return false;
        final java.lang.Object this$globalToSubspace = this.getGlobalToSubspace();
        final java.lang.Object other$globalToSubspace = other.getGlobalToSubspace();
        if (this$globalToSubspace == null ? other$globalToSubspace != null : !this$globalToSubspace.equals(other$globalToSubspace)) return false;
        if (java.lang.Double.compare(this.getPosX(), other.getPosX()) != 0) return false;
        if (java.lang.Double.compare(this.getPosY(), other.getPosY()) != 0) return false;
        if (java.lang.Double.compare(this.getPosZ(), other.getPosZ()) != 0) return false;
        final java.lang.Object this$centerCoord = this.getCenterCoord();
        final java.lang.Object other$centerCoord = other.getCenterCoord();
        if (this$centerCoord == null ? other$centerCoord != null : !this$centerCoord.equals(other$centerCoord)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ShipTransform;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $subspaceToGlobal = this.getSubspaceToGlobal();
        result = result * PRIME + ($subspaceToGlobal == null ? 43 : $subspaceToGlobal.hashCode());
        final java.lang.Object $globalToSubspace = this.getGlobalToSubspace();
        result = result * PRIME + ($globalToSubspace == null ? 43 : $globalToSubspace.hashCode());
        final long $posX = java.lang.Double.doubleToLongBits(this.getPosX());
        result = result * PRIME + (int) ($posX >>> 32 ^ $posX);
        final long $posY = java.lang.Double.doubleToLongBits(this.getPosY());
        result = result * PRIME + (int) ($posY >>> 32 ^ $posY);
        final long $posZ = java.lang.Double.doubleToLongBits(this.getPosZ());
        result = result * PRIME + (int) ($posZ >>> 32 ^ $posZ);
        final java.lang.Object $centerCoord = this.getCenterCoord();
        result = result * PRIME + ($centerCoord == null ? 43 : $centerCoord.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ShipTransform(subspaceToGlobal=" + this.getSubspaceToGlobal() + ", globalToSubspace=" + this.getGlobalToSubspace() + ", posX=" + this.getPosX() + ", posY=" + this.getPosY() + ", posZ=" + this.getPosZ() + ", centerCoord=" + this.getCenterCoord() + ")";
    }

    /**
     * A transformation matrix used to convert 'subspace' coordinates into 'global' coordinates.
     */
    @java.lang.SuppressWarnings("all")
    public ShipTransform withSubspaceToGlobal(final Matrix4dc subspaceToGlobal) {
        return this.subspaceToGlobal == subspaceToGlobal ? this : new ShipTransform(subspaceToGlobal, this.globalToSubspace, this.posX, this.posY, this.posZ, this.centerCoord);
    }

    /**
     * A transformation matrix used to convert 'global' coordinates into 'subspace coordinates'
     */
    @java.lang.SuppressWarnings("all")
    public ShipTransform withGlobalToSubspace(final Matrix4dc globalToSubspace) {
        return this.globalToSubspace == globalToSubspace ? this : new ShipTransform(this.subspaceToGlobal, globalToSubspace, this.posX, this.posY, this.posZ, this.centerCoord);
    }

    @java.lang.SuppressWarnings("all")
    public ShipTransform withPosX(final double posX) {
        return this.posX == posX ? this : new ShipTransform(this.subspaceToGlobal, this.globalToSubspace, posX, this.posY, this.posZ, this.centerCoord);
    }

    @java.lang.SuppressWarnings("all")
    public ShipTransform withPosY(final double posY) {
        return this.posY == posY ? this : new ShipTransform(this.subspaceToGlobal, this.globalToSubspace, this.posX, posY, this.posZ, this.centerCoord);
    }

    @java.lang.SuppressWarnings("all")
    public ShipTransform withPosZ(final double posZ) {
        return this.posZ == posZ ? this : new ShipTransform(this.subspaceToGlobal, this.globalToSubspace, this.posX, this.posY, posZ, this.centerCoord);
    }

    @java.lang.SuppressWarnings("all")
    public ShipTransform withCenterCoord(final Vector3dc centerCoord) {
        return this.centerCoord == centerCoord ? this : new ShipTransform(this.subspaceToGlobal, this.globalToSubspace, this.posX, this.posY, this.posZ, centerCoord);
    }

    @java.lang.SuppressWarnings("all")
    public ShipTransform(final Matrix4dc subspaceToGlobal, final Matrix4dc globalToSubspace, final double posX, final double posY, final double posZ, final Vector3dc centerCoord) {
        this.subspaceToGlobal = subspaceToGlobal;
        this.globalToSubspace = globalToSubspace;
        this.posX = posX;
        this.posY = posY;
        this.posZ = posZ;
        this.centerCoord = centerCoord;
    }

    @java.lang.SuppressWarnings("all")
    private ShipTransform() {
        this.subspaceToGlobal = null;
        this.globalToSubspace = null;
        this.posX = 0.0;
        this.posY = 0.0;
        this.posZ = 0.0;
        this.centerCoord = null;
    }
}
