// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common;

import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.IRecipe;
import net.minecraft.item.crafting.ShapedRecipes;
import net.minecraft.server.MinecraftServer;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.common.crafting.CraftingHelper;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.FMLLog;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.SidedProxy;
import zmaster587.advancedRocketry.api.Constants;
import net.minecraftforge.fml.common.event.*;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.relauncher.Side;
import org.valkyrienskies.mod.client.gui.TabValkyrienSkies;
import org.valkyrienskies.mod.common.block.BlockBoatChair;
import org.valkyrienskies.mod.common.block.BlockCaptainsChair;
import org.valkyrienskies.mod.common.block.BlockPassengerChair;
import org.valkyrienskies.mod.common.block.BlockWaterPump;
import org.valkyrienskies.mod.common.capability.VSCapabilityRegistry;
import org.valkyrienskies.mod.common.command.framework.VSCommandRegistry;
import org.valkyrienskies.mod.common.config.VSConfig;
import org.valkyrienskies.mod.common.item.ItemShipTracker;
import org.valkyrienskies.mod.common.network.*;
import org.valkyrienskies.mod.common.piloting.PilotControlsMessage;
import org.valkyrienskies.mod.common.piloting.PilotControlsMessageHandler;
import org.valkyrienskies.mod.common.ships.deprecated_api.VS_APIPhysicsEntityManager;
import org.valkyrienskies.mod.common.tileentity.TileEntityBoatChair;
import org.valkyrienskies.mod.common.tileentity.TileEntityCaptainsChair;
import org.valkyrienskies.mod.common.tileentity.TileEntityPassengerChair;
import org.valkyrienskies.mod.common.tileentity.TileEntityWaterPump;
import org.valkyrienskies.mod.fixes.darkness_lib_fix.VSDarknessLibAPILightProvider;
import org.valkyrienskies.mod.proxy.CommonProxy;
import valkyrienwarfare.api.IPhysicsEntityManager;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ForkJoinPool;
import java.util.function.Function;

// NOT an @Mod. Valkyrien Skies is vendored into Advanced Rocketry and hosted by AR's single
// mod container: AR's lifecycle handlers drive this class's preInit/init/postInit/serverStart,
// and its @Mod.EventBusSubscriber handlers are owned by AR's modid (see HOST_MOD_ID). Being a
// second @Mod in one jar broke every FML mechanism that partitions by mod (sided-proxy and
// event-bus-subscriber owner resolution match the target class name against the @Mod class name).
public class ValkyrienSkiesMod {
	@java.lang.SuppressWarnings("all")
	private static final org.apache.logging.log4j.Logger log = org.apache.logging.log4j.LogManager.getLogger(ValkyrienSkiesMod.class);
	// Used for registering stuff
	public static final List<Block> BLOCKS = new ArrayList<>();
	public static final List<Item> ITEMS = new ArrayList<>();
	// MOD INFO CONSTANTS
	// MOD_ID is "valkyrienskies". HOST_MOD_ID is the modid of the mod that actually owns VS's
	// lifecycle and event-bus subscriptions now — Advanced Rocketry.
	//
	// THIS COMMENT USED TO SAY MOD_ID WAS "the registry DOMAIN for VS blocks/items/entities and the
	// assets path". IT IS NOT, AND MEASURING IT IS HOW A LIVE BUG WAS FOUND (2026-09-22). The domain
	// is whatever each registration ASKS for, and the registrations here do not agree:
	//   - TILE ENTITIES pass `new ResourceLocation(MOD_ID, …)` explicitly  -> valkyrienskies:…
	//   - BLOCKS and ITEMS reach the registry through BaseBlock/BaseItem, which call
	//     `setRegistryName(name)` with a BARE string -> Forge resolves it against the ACTIVE mod
	//     container, which for a vendored mod is the HOST: advancedrocketry:…
	//   - ASSETS sit under assets/valkyrienskies/, which is where neither of the above looks for a
	//     block model.
	// The client says both halves out loud on every boot: "Potentially Dangerous alternative prefix
	// `valkyrienskies` for name `tile_captains_chair`, expected `advancedrocketry`" for the first,
	// and "FileNotFoundException: advancedrocketry:models/item/vs_ship_tracker.json" for the second.
	// Every block registered through BaseBlock therefore draws as the missing model. Not fixed here:
	// the fix is an explicit domain or a moved asset root, and which one is a decision about where a
	// vendored mod's assets live. `VendoredAssetDomainTest` pins the state until it is taken.
	public static final String MOD_ID = "valkyrienskies";
	public static final String HOST_MOD_ID = Constants.modId;
	static final String MOD_FINGERPRINT = "b308676914a5e7d99459c1d2fb298744387899a7";
	// MOD INSTANCE — self-initialised (no @Instance: there is no "valkyrienskies" mod container to
	// inject from). Ready at class-load, before any registry event references it.
	public static ValkyrienSkiesMod INSTANCE = new ValkyrienSkiesMod();
	// modId names AR's container so FML injects this proxy as part of AR's mod (VS is not its own mod).
	@SidedProxy(modId = HOST_MOD_ID, clientSide = "org.valkyrienskies.mod.proxy.ClientProxy", serverSide = "org.valkyrienskies.mod.proxy.ServerProxy")
	public static CommonProxy proxy;
	static final int VS_ENTITY_LOAD_DISTANCE = 128;
	/**
	 * This service is directly responsible for running collision tasks.
	 */
	private static ForkJoinPool physicsThreadPool = null;
	public Block captainsChair;
	public Block passengerChair;
	public Block waterPump;
	public Block boatChair;
	public Item shipTracker;
	public static SimpleNetworkWrapper physWrapperNetwork;
	public static SimpleNetworkWrapper physWrapperTransformUpdateNetwork;
	public static SimpleNetworkWrapper controlNetwork;
	public static final CreativeTabs VS_CREATIVE_TAB = new TabValkyrienSkies(MOD_ID);
	// Add-on module detection (the "vs_control" / "vs_world" list, its isAnyModuleLoaded flag and
	// accessor, and the login warning that consumed them) removed: this physics core is vendored as
	// part of this mod rather than shipped as a platform for those add-ons, so there is nothing to
	// detect and nothing to recommend installing.

	// onFingerprintViolation removed: VS is vendored into AR (unsigned, integrated),
	// so the JAR-signature check is meaningless; its body also referenced the coremod
	// class MixinLoaderForge, which lives in the mixin-owned package
	// org.valkyrienskies.mixin.* and cannot be referenced from ordinary (non-mixin) code.

	public void preInit(FMLPreInitializationEvent event) {
		log.debug("Initializing configuration.");
		runConfiguration();
		log.debug("Instantiating the physics thread executor.");
		ValkyrienSkiesMod.physicsThreadPool = new ForkJoinPool(VSConfig.threadCount);
		log.debug("Initializing networks.");
		registerNetworks(event);
		VSCapabilityRegistry.registerCapabilities();
		proxy.preInit(event);
		log.debug("Initializing the VS API.");
		try {
			Field instanceField = IPhysicsEntityManager.class.getDeclaredField("INSTANCE");
			// Make the field accessible
			instanceField.setAccessible(true);
			// Remove the final modifier
			Field modifiersField = Field.class.getDeclaredField("modifiers");
			modifiersField.setAccessible(true);
			modifiersField.setInt(instanceField, instanceField.getModifiers() & ~Modifier.FINAL);
			// Finally set the new value of the field.
			instanceField.set(null, new VS_APIPhysicsEntityManager());
		} catch (Exception e) {
			e.printStackTrace();
			log.fatal("FAILED TO INITIALIZE VS API!");
		}
		registerItems();
		registerBlocks();
		registerDarknessLib();
	}

	private void registerDarknessLib() {
		// Register light provider with DarknessLib
		try {
			// Why yes, I am using some hacky reflection. I know theres an IMCEvent way to do it, but I can't get it to
			// work no matter what I do! So reflection it is!
			final Class clazz = Class.forName("com.shinoow.darknesslib.api.DarknessLibAPI");
			final Field instanceField = clazz.getDeclaredField("INSTANCE");
			final Field lightProvidersField = clazz.getDeclaredField("LIGHT_PROVIDERS");
			// Remove private from the fields
			instanceField.setAccessible(true);
			lightProvidersField.setAccessible(true);
			// Finally add the light provider
			final Object instance = instanceField.get(null);
			final List<Function<EntityPlayer, Integer>> lightProviders = (List<Function<EntityPlayer, Integer>>) lightProvidersField.get(instance);
			lightProviders.add(new VSDarknessLibAPILightProvider());
		} catch (Exception e) {
		}
	}

	public void init(FMLInitializationEvent event) {
		log.info("Valkyrien Skies Initialization: We are running on {} threads; 4 or more is recommended!", Runtime.getRuntime().availableProcessors());
		proxy.init(event);
		isSpongePresent = Loader.isModLoaded("spongeforge");
	}

	public void postInit(FMLPostInitializationEvent event) {
		proxy.postInit(event);
	}

	public void serverStart(FMLServerStartingEvent event) {
		MinecraftServer server = event.getServer();
		VSCommandRegistry.registerCommands(server);
	}

	private void registerNetworks(FMLStateEvent event) {
		physWrapperNetwork = NetworkRegistry.INSTANCE.newSimpleChannel("valkyrien_skies");
		physWrapperNetwork.registerMessage(ShipIndexDataMessageHandler.class, ShipIndexDataMessage.class, 0, Side.CLIENT);
		controlNetwork = NetworkRegistry.INSTANCE.newSimpleChannel("valkyrien_piloting");
		controlNetwork.registerMessage(PilotControlsMessageHandler.class, PilotControlsMessage.class, 0, Side.SERVER);
		controlNetwork.registerMessage(MessageStartPilotingHandler.class, MessageStartPiloting.class, 1, Side.CLIENT);
		controlNetwork.registerMessage(MessageStopPilotingHandler.class, MessageStopPiloting.class, 2, Side.CLIENT);
		controlNetwork.registerMessage(MessagePlayerStoppedPilotingHandler.class, MessagePlayerStoppedPiloting.class, 3, Side.SERVER);
		physWrapperTransformUpdateNetwork = NetworkRegistry.INSTANCE.newSimpleChannel("vs_ship_transforms");
		physWrapperTransformUpdateNetwork.registerMessage(ShipTransformUpdateMessageHandler.class, ShipTransformUpdateMessage.class, 0, Side.CLIENT);
	}

	void registerRecipes(RegistryEvent.Register<IRecipe> event) {
		if (!VSConfig.chairRecipes) return;
		registerRecipe(event, "recipe_captains_chair", new ItemStack(captainsChair), "SLS", "VWV", " S ", 'S', Items.STICK, 'L', Items.LEATHER, 'W', Item.getItemFromBlock(Blocks.LOG), 'V', Items.DIAMOND);
		registerRecipe(event, "recipe_passenger_chair", new ItemStack(passengerChair), "SLS", "PWP", " S ", 'S', Items.STICK, 'L', Items.LEATHER, 'W', Item.getItemFromBlock(Blocks.LOG), 'P', Item.getItemFromBlock(Blocks.PLANKS));
	}

	private static void registerRecipe(RegistryEvent.Register<IRecipe> event, String registryName, ItemStack out, Object... in) {
		CraftingHelper.ShapedPrimer primer = CraftingHelper.parseShaped(in);
		event.getRegistry().register(new ShapedRecipes(ValkyrienSkiesMod.MOD_ID, primer.width, primer.height, primer.input, out).setRegistryName(ValkyrienSkiesMod.MOD_ID, registryName));
	}

	/**
	 * Initializes the configuration - {@link VSConfig}
	 */
	private void runConfiguration() {
		VSConfig.sync();
	}

	private void registerTileEntities() {
		GameRegistry.registerTileEntity(TileEntityCaptainsChair.class, new ResourceLocation(MOD_ID, "tile_captains_chair"));
		GameRegistry.registerTileEntity(TileEntityPassengerChair.class, new ResourceLocation(MOD_ID, "tile_passenger_chair"));
		GameRegistry.registerTileEntity(TileEntityWaterPump.class, new ResourceLocation(MOD_ID, "tile_water_pump"));
		GameRegistry.registerTileEntity(TileEntityBoatChair.class, new ResourceLocation(MOD_ID, "tile_boat_chair"));
	}

	private void registerBlocks() {
		this.captainsChair = registerBlock(new BlockCaptainsChair());
		this.passengerChair = registerBlock(new BlockPassengerChair());
		this.waterPump = registerBlock(new BlockWaterPump());
		this.boatChair = registerBlock(new BlockBoatChair());
		this.registerTileEntities();
	}

	private Block registerBlock(Block block) {
		ValkyrienSkiesMod.BLOCKS.add(block);
		ValkyrienSkiesMod.ITEMS.add(new ItemBlock(block).setRegistryName(block.getRegistryName()));
		return block;
	}

	private void registerItems() {
		this.shipTracker = new ItemShipTracker("vs_ship_tracker", true);
	}

	private static boolean isSpongePresent = false;

	/**
	 * This service is directly responsible for running collision tasks.
	 */
	@java.lang.SuppressWarnings("all")
	public static ForkJoinPool getPhysicsThreadPool() {
		return ValkyrienSkiesMod.physicsThreadPool;
	}

	@java.lang.SuppressWarnings("all")
	public static boolean isSpongePresent() {
		return ValkyrienSkiesMod.isSpongePresent;
	}
}
