// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.util.names;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.ThreadLocalRandom;
import java.util.stream.Collectors;

/**
 * Generates names from a noun list
 */
public class NounListNameGenerator implements NameGenerator {
    private static final int NOUN_LIST_LENGTH = 6801;
    private static final int DEFAULT_NOUNS_PER_NAME = 3;
    /** Effectively final, process lifetime: set once when the object is built. */
    private final List<String> nouns = new ArrayList<>(NOUN_LIST_LENGTH);
    /** Effectively final, process lifetime: built once at class initialisation. */
    private static final NounListNameGenerator instance = new NounListNameGenerator();

    private NounListNameGenerator() {
        try {
            BufferedReader reader = new BufferedReader(new InputStreamReader(Objects.requireNonNull(getClass().getClassLoader().getResourceAsStream("assets/valkyrienskies/nounlist.txt"))));
            String line;
            while ((line = reader.readLine()) != null) {
                nouns.add(line);
            }
        } catch (final java.lang.Throwable $ex) {
            throw new RuntimeException($ex);
        }
    }

    @Override
    public String generateName() {
        return this.generateName(DEFAULT_NOUNS_PER_NAME);
    }

    public String generateName(int numberOfNouns) {
        return ThreadLocalRandom.current().ints(numberOfNouns, 0, nouns.size()).mapToObj(nouns::get).collect(Collectors.joining("-"));
    }

    @java.lang.SuppressWarnings("all")
    public static NounListNameGenerator getInstance() {
        return NounListNameGenerator.instance;
    }
}
