package dev.stannismod.stellurgy.space;

import net.minecraftforge.client.IRenderHandler;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import dev.stannismod.stellurgy.client.render.planet.BoundarySky;
import dev.stannismod.stellurgy.world.provider.WorldProviderSpace;

/**
 * Pool-slot space world provider: a reusable empty-space world whose ON-DISK chunk
 * directory is chosen by the CELL currently bound to this slot, not by the dimension id.
 *
 * <p>One pre-registered "slot" dimension can therefore host different logical space cells
 * over time: {@code AnvilSaveHandler.getChunkLoader} builds the chunk loader from
 * {@link #getSaveFolder()}, so returning the bound cell's folder here retargets where this
 * world reads and writes chunks. Rebinding a slot to another cell (see {@link SpaceSlotPool})
 * flushes, changes the binding, and reinitialises the dimension so the loader is rebuilt
 * against the new folder. Empty space is generated by the inherited
 * {@link WorldProviderSpace} (void by default).</p>
 */
public class WorldProviderSpaceSlot extends WorldProviderSpace {

    // Lazily-built descent-boundary sky renderer for this slot (client-only; cached per provider
    // instance, never rebuilt per frame). Mirrors the private-field lazy pattern of the parent
    // WorldProviderSpace, since super.getSkyRenderer() runs the rocket/station sky logic we replace.
    private IRenderHandler boundarySky;

    @Override
    @SideOnly(Side.CLIENT)
    public IRenderHandler getSkyRenderer() {
        if (boundarySky == null)
            boundarySky = new BoundarySky();
        return boundarySky;
    }

    @Override
    public String getSaveFolder() {
        String cell = SpaceSlotPool.cellKeyFor(getDimension());
        // Unbound slot -> a private per-slot scratch folder; bound -> the cell's shared folder
        // (two slots must never bind the same cell simultaneously -- the pool enforces that). The unbound
        // path goes through SpaceSlotPool so the hyperspace-folder wipe (deleteUnboundSlotStore) provably
        // targets the exact folder this provider reads/writes.
        if (cell != null) {
            return "advRocketry/spacepool/cell_" + cell;
        }
        // The one unbound slot that is not scratch: hyperspace holds every ship in flight and now
        // outlives the server, so its content is named after the world rather than after whichever
        // dimension id this boot's free-id scan handed it.
        return getDimension() == dev.stannismod.stellurgy.Stellurgy.serverState().hyperspace.dimId()
                ? SpaceSlotPool.hyperspaceSubfolder()
                : SpaceSlotPool.unboundSlotSubfolder(getDimension());
    }
}
