// Generated by delombok at Fri Jul 24 15:34:08 MSK 2026
package org.valkyrienskies.mod.common.util;

import mcp.MethodsReturnNonnullByDefault;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLiving;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.projectile.EntityFireball;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.util.Tuple;
import net.minecraft.util.math.AxisAlignedBB;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.Vec3d;
import net.minecraft.world.World;
import net.minecraft.world.WorldServer;
import net.minecraft.world.chunk.Chunk;
import org.joml.Matrix4dc;
import org.joml.Vector3d;
import org.joml.Vector3dc;
import org.valkyrienskies.mod.common.capability.VSCapabilityRegistry;
import org.valkyrienskies.mod.common.capability.VSWorldDataCapability;
import org.valkyrienskies.mod.common.collision.Polygon;
import org.valkyrienskies.mod.common.entity.EntityMountable;
import org.valkyrienskies.mod.common.entity.EntityShipMovementData;
import org.valkyrienskies.mod.common.ships.QueryableShipData;
import org.valkyrienskies.mod.common.ships.ShipData;
import org.valkyrienskies.mod.common.ships.block_relocation.BlockFinder;
import org.valkyrienskies.mod.common.ships.chunk_claims.ShipChunkAllocator;
import org.valkyrienskies.mod.common.ships.chunk_claims.VSChunkClaim;
import org.valkyrienskies.mod.common.ships.entity_interaction.EntityShipMountData;
import org.valkyrienskies.mod.common.ships.entity_interaction.IDraggable;
import org.valkyrienskies.mod.common.ships.ship_transform.CoordinateSpaceType;
import org.valkyrienskies.mod.common.ships.ship_transform.ShipTransform;
import org.valkyrienskies.mod.common.ships.ship_world.IHasShipManager;
import org.valkyrienskies.mod.common.ships.ship_world.IPhysObjectWorld;
import org.valkyrienskies.mod.common.ships.ship_world.PhysicsObject;
import org.valkyrienskies.mod.common.ships.ship_world.WorldServerShipManager;
import org.valkyrienskies.mod.common.util.names.NounListNameGenerator;
import valkyrienwarfare.api.TransformType;
import javax.annotation.Nullable;
import javax.annotation.ParametersAreNonnullByDefault;
import java.util.Optional;
import java.util.UUID;

/**
 * This class contains various helper functions for Valkyrien Skies.
 */
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
public final class ValkyrienUtils {

    /**
     * How far from a hull a body may be and still count as at it, in blocks. Not chosen here: it is
     * the expansion {@code EntityCollisionInjector.getCollidingPolygonsAndDoBlockCols} already puts
     * on an entity's box before asking which ships it might touch, which is the query that decides
     * an entity is aboard in the first place.
     */
    public static final double SHIP_DRAG_REACH_BLOCKS = 1.0d;

    /**
     * The liver of this mod. Returns the PhysicsObject that managed the given pos in the given
     * world.
     *
     * @param world The World we are in
     * @param pos   A BlockPos within the physics object space.
     * @return The PhysicsObject that owns the chunk at pos within the given world.
     */
    @SuppressWarnings("ConstantConditions")
    public static Optional<PhysicsObject> getPhysoManagingBlock(@Nullable World world, @Nullable BlockPos pos) {
        return getShipManagingBlock(world, pos).map(shipData -> getPhysObjWorld(world).getPhysObjectFromUUID(shipData.getUuid()));
    }

    public static Optional<PhysicsObject> getPhysoManagingBlockThreadSafe(@Nullable World world, @Nullable BlockPos pos) {
        for (PhysicsObject physicsObject : getPhysObjWorld(world).getAllLoadedThreadSafe()) {
            if (physicsObject.getChunkClaim().containsBlock(pos)) {
                return Optional.of(physicsObject);
            }
        }
        return Optional.empty();
    }

    public static Optional<ShipData> getShipManagingBlock(@Nullable World world, @Nullable BlockPos pos) {
        if (world == null || pos == null || !ShipChunkAllocator.isChunkInShipyard(pos.getX() >> 4, pos.getZ() >> 4)) {
            return Optional.empty();
        }
        return QueryableShipData.get(world).getShipFromChunk(pos.getX() >> 4, pos.getZ() >> 4);
    }

    /**
     * If the given AxisAlignedBB is in ship space, then this will return that AxisAlignedBB
     * transformed to global space. Otherwise it just returns the input AxisAlignedBB.
     */
    public static AxisAlignedBB getAABBInGlobal(AxisAlignedBB axisAlignedBB, @Nullable World world, @Nullable BlockPos pos) {
        Optional<PhysicsObject> physicsObject = ValkyrienUtils.getPhysoManagingBlock(world, pos);
        if (physicsObject.isPresent()) {
            // We're in a physics object; convert the bounding box to a polygon; put its coordinates
            // in global space, and then return the bounding box that encloses all the points.
            Polygon bbAsPoly = new Polygon(axisAlignedBB, physicsObject.get().getShipTransformationManager().getCurrentTickTransform(), TransformType.SUBSPACE_TO_GLOBAL);
            return bbAsPoly.getEnclosedAABB();
        } else {
            return axisAlignedBB;
        }
    }

    public static EntityShipMountData getMountedShipAndPos(Entity entity) {
        Entity ridingEntity = entity.ridingEntity;
        if (ridingEntity instanceof EntityMountable) {
            EntityMountable mountable = (EntityMountable) ridingEntity;
            Optional<PhysicsObject> mountedShip = mountable.getMountedShip();
            if (mountedShip.isPresent()) {
                return new EntityShipMountData(mountedShip.get(), mountable.getMountPos());
            }
        }
        return new EntityShipMountData();
    }

    public static void fixEntityToShip(Entity toFix, Vector3dc posInLocal, PhysicsObject mountingShip) {
        World world = mountingShip.getWorld();
        EntityMountable entityMountable = new EntityMountable(world, JOML.toMinecraft(posInLocal), CoordinateSpaceType.SUBSPACE_COORDINATES, mountingShip.getReferenceBlockPos());
        world.spawnEntity(entityMountable);
        toFix.startRiding(entityMountable);
    }

    private static VSWorldDataCapability getWorldDataCapability(World world) {
        VSWorldDataCapability worldData = world.getCapability(VSCapabilityRegistry.VS_WORLD_DATA, null);
        if (worldData == null) {
            // I hate it when other mods add their custom worlds without calling the forge world
            // load events, so I don't feel bad crashing the game here. Although we could also get
            // away with just adding the capability to world instead of crashing.
            throw new IllegalStateException("World " + world + " doesn\'t have an VSWorldDataCapability. This is wrong!");
        }
        return worldData;
    }

    /**
     * This method basically grabs the {@link VSWorldDataCapability} capability from the world
     * and then returns the {@link QueryableShipData} associated with it
     *
     * @param world The world we are getting the QueryableShipData from
     * @return The QueryableShipData corresponding to the given world
     */
    public static QueryableShipData getQueryableData(World world) {
        return getWorldDataCapability(world).get().getQueryableShipData();
    }

    /**
     * This method basically grabs the {@link VSWorldDataCapability} capability from the world
     * and then returns the {@link ShipChunkAllocator} associated with it
     *
     * @param world The world we are getting the QueryableShipData from
     * @return The QueryableShipData corresponding to the given world
     */
    public static ShipChunkAllocator getShipChunkAllocator(World world) {
        return getWorldDataCapability(world).get().getShipChunkAllocator();
    }

    public static WorldServerShipManager getServerShipManager(World world) {
        return (WorldServerShipManager) ((IHasShipManager) world).getManager();
    }

    /**
     * Creates a new ShipIndexedData based on the inputs provided by the physics infuser block.
     */
    public static ShipData createNewShip(World world, BlockPos physInfuserPos) {
        return createNewShip(world, physInfuserPos, UUID.randomUUID());
    }

    /**
     * The same, with the ship's identity CHOSEN by the caller instead of minted here.
     *
     * <p>A ship that is taken apart in one world and re-assembled in another is the same ship to the
     * player, and a fresh identity per re-assembly is what forces everything downstream to re-find it
     * by position. The identity is a plain parameter of {@link ShipData#createData} and always was;
     * this overload only exposes it, and the no-uuid form above is now this one with a random value.
     *
     * <p><b>The uuid must be free in {@code world}</b>: the registry indexes it uniquely, so adding a
     * second ship under a live one's identity throws when the spawn is drained. A caller re-assembling
     * a ship it has just cut out of another world is responsible for the blockless remnant of that
     * ship here, if one exists.
     */
    public static ShipData createNewShip(World world, BlockPos physInfuserPos, UUID shipID) {
        String name = NounListNameGenerator.getInstance().generateName();
        // Create ship chunk claims
        VSChunkClaim chunkClaim = ValkyrienUtils.getShipChunkAllocator(world).allocateNextChunkClaim();
        Vector3dc centerOfMassInitial = VSMath.toVector3d(chunkClaim.getRegionCenter());
        Vector3dc shipPosInitial = VSMath.toVector3d(physInfuserPos);
        ShipTransform initial = new ShipTransform(shipPosInitial, centerOfMassInitial);
        AxisAlignedBB axisAlignedBB = new AxisAlignedBB(shipPosInitial.x(), shipPosInitial.y(), shipPosInitial.z(), shipPosInitial.x(), shipPosInitial.y(), shipPosInitial.z());
        return ShipData.createData(QueryableShipData.get(world).getAllShips(), name, chunkClaim, shipID, initial, axisAlignedBB);
    }

    public static Iterable<PhysicsObject> getPhysosLoadedInWorld(World world) {
        return ((IHasShipManager) world).getManager().getAllLoadedPhysObj();
    }

    public static void assembleShipAsOrderedByPlayer(World world, @Nullable EntityPlayerMP creator, BlockPos physicsInfuserPos, BlockFinder.BlockFinderType blockFinderType) {
        if (world.isRemote) {
            throw new IllegalStateException("This method cannot be invoked on client side!");
        }
        if (!(world instanceof WorldServer)) {
            throw new IllegalStateException("The world " + world + " wasn\'t an instance of WorldServer");
        }
        // Create the ship data that we will use to make the ship with later.
        ShipData shipData = createNewShip(world, physicsInfuserPos);
        // Queue the ship spawn operation
        ((WorldServerShipManager) ValkyrienUtils.getPhysObjWorld(world)).queueShipSpawn(shipData, physicsInfuserPos, blockFinderType);
    }

    public static IPhysObjectWorld getPhysObjWorld(World world) {
        return ((IHasShipManager) world).getManager();
    }

    /**
     * Applies the given transform matrix to the position/velocity/look of the given entity.
     * @param transform The transform matrix to be applied.
     * @param entity The entity that will be transformed.
     */
    public static void transformEntity(final Matrix4dc transform, final Entity entity, final boolean transformEntityBoundingBox) {
        Vec3d entityLookMc = entity.getLook(1.0F);
        Vector3d entityPos = new Vector3d(entity.posX, entity.posY, entity.posZ);
        Vector3d entityLook = new Vector3d(entityLookMc.x, entityLookMc.y, entityLookMc.z);
        Vector3d entityMotion = new Vector3d(entity.motionX, entity.motionY, entity.motionZ);
        if (entity instanceof EntityFireball) {
            EntityFireball ball = (EntityFireball) entity;
            entityMotion.x = ball.accelerationX;
            entityMotion.y = ball.accelerationY;
            entityMotion.z = ball.accelerationZ;
        }
        transform.transformPosition(entityPos);
        transform.transformDirection(entityLook);
        transform.transformDirection(entityMotion);
        entityLook.normalize();
        // This is correct, works properly when tested with cows
        if (entity instanceof EntityLiving) {
            EntityLiving living = (EntityLiving) entity;
            living.rotationYawHead = entity.rotationYaw;
            living.prevRotationYawHead = entity.rotationYaw;
        }
        // Get the player pitch/yaw from the look vector
        final Tuple<Double, Double> pitchYawTuple = VSMath.getPitchYawFromVector(new Vector3d(entityLook.x, entityLook.y, entityLook.z));
        entity.rotationPitch = pitchYawTuple.getFirst().floatValue();
        entity.rotationYaw = pitchYawTuple.getSecond().floatValue();
        if (entity instanceof EntityFireball) {
            EntityFireball ball = (EntityFireball) entity;
            ball.accelerationX = entityMotion.x;
            ball.accelerationY = entityMotion.y;
            ball.accelerationZ = entityMotion.z;
        }
        entity.motionX = entityMotion.x;
        entity.motionY = entityMotion.y;
        entity.motionZ = entityMotion.z;
        if (transformEntityBoundingBox) {
            // Transform the bounding box too
            final AxisAlignedBB oldBB = entity.getEntityBoundingBox();
            final Polygon newBBPoly = new Polygon(oldBB, transform);
            final AxisAlignedBB newBB = newBBPoly.getEnclosedAABB();
            final double oldBBSize = (oldBB.maxX - oldBB.minX) * (oldBB.maxY - oldBB.minY) * (oldBB.maxZ - oldBB.minZ);
            final double newBBSize = (newBB.maxX - newBB.minX) * (newBB.maxY - newBB.minY) * (newBB.maxZ - newBB.minZ);
            final double scaleFactor = Math.pow(oldBBSize / newBBSize, 1.0 / 3.0);
            // Scale the bounding box such that the new bounding box is the same size as the old bounding box.
            final AxisAlignedBB newBBScaled = newBB.grow((scaleFactor - 1) * (newBB.maxX - newBB.minX) / 2.0, (scaleFactor - 1) * (newBB.maxY - newBB.minY) / 2.0, (scaleFactor - 1) * (newBB.maxZ - newBB.minZ) / 2.0);
            entity.setPosition(entityPos.x, entityPos.y, entityPos.z);
            entity.setEntityBoundingBox(newBBScaled);
        } else {
            // Just use the regular bounding box
            entity.setPosition(entityPos.x, entityPos.y, entityPos.z);
        }
    }

    /**
     * Used for bad code that tries reading tile entities from a non game thread. But hey it works (mostly).
     */
    @Nullable
    public static TileEntity getTileEntitySafe(World world, BlockPos pos) {
        return world.getChunkFromBlockCoords(pos).getTileEntity(pos, Chunk.EnumCreateEntityType.CHECK);
    }

    /**
     * Whether {@code entity} is still at the hull of {@code ship} — the question a drag path must
     * ask before treating a body as CARRIED by that ship.
     *
     * <p>The association between a body and the last ship it touched is a TIMER, and a timer cannot
     * tell that the body has since been moved somewhere else: a teleport writes a position without
     * routing through {@code Entity.move}, which is the only place the association is re-evaluated.
     * That matters because the drag transforms the body by the hull's rigid between-tick motion, and
     * a rigid motion's displacement at a point grows with that point's distance from the hull — a
     * hull turning a degree per tick writes a block per tick at sixty blocks away and eighty blocks
     * per tick at four and a half thousand. So the timer alone is not a sufficient licence to move a
     * body, and the bound that IS sufficient belongs to the ship: its own extent.
     *
     * <p><b>The reach is not a new number.</b> It is the one the substrate already uses to decide
     * which ships matter to an entity at all — {@code EntityCollisionInjector
     * .getCollidingPolygonsAndDoBlockCols} grows the entity's box by {@code expand(1, 1, 1)} before
     * asking {@code getPhysObjectsInAABB} — and that query is what CREATES the association this
     * predicate re-checks. Applied to the ship's box instead of the entity's, and symmetrically,
     * because the question here is proximity rather than a swept movement.
     *
     * <p><b>What this deliberately does NOT keep carrying.</b> A body further than that from the
     * hull — past the apex of a jump off a level deck, say — stops being offered a new delta and
     * falls to the same treatment as one whose timer ran out: it keeps the velocity it already had,
     * decaying. For a ship in steady motion that is the same landing spot; the difference shows only
     * on a hull accelerating or turning under a body that is no longer on it, which is momentum the
     * body has no contact to receive.
     */
    public static boolean isEntityWithinShipBounds(final Entity entity, final ShipData ship) {
        if (entity == null || ship == null) {
            return false;
        }
        final AxisAlignedBB shipBB = ship.getShipBB();
        return shipBB != null && isWithinShipBounds(entity.getEntityBoundingBox(), shipBB);
    }

    /**
     * The geometry behind {@link #isEntityWithinShipBounds(Entity, ShipData)}, split out so the one
     * thing that can silently go wrong here — the boundary — is checkable without a world, a ship or
     * an entity.
     *
     * <p>That boundary is not academic. A ship's box is built from integer block coordinates grown
     * only on its max side ({@code makeAABB().expand(1, 1, 1)}), so its top face lands exactly on the
     * block grid, and a body STANDING on the topmost deck block has its own minimum on that same
     * line. {@link AxisAlignedBB#intersects} is strict on every axis and answers "not overlapping"
     * for boxes that meet exactly — which would refuse the one posture the drag exists to serve. The
     * reach carries the comparison clear of that line instead of leaving it to a tie.
     */
    public static boolean isWithinShipBounds(final AxisAlignedBB body, final AxisAlignedBB shipBB) {
        return body.intersects(shipBB.grow(SHIP_DRAG_REACH_BLOCKS));
    }

    @Nullable
    public static ShipData getLastShipTouchedByEntity(final Entity entity) {
        final IDraggable asDraggable = IDraggable.class.cast(entity);
        return asDraggable.getEntityShipMovementData().getLastTouchedShip();
    }

    
    public static EntityShipMovementData getEntityShipMovementDataFor(final Entity entity) {
        final IDraggable asDraggable = IDraggable.class.cast(entity);
        return asDraggable.getEntityShipMovementData();
    }

    @java.lang.SuppressWarnings("all")
    private ValkyrienUtils() {
        throw new java.lang.UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }
}
